### ISSUE TITLE
Deployed Go app with Dockerfile and Deis didn't used right port on service when deploying app

### ISSUE THREAD

**Issue by felipejfc** [deis/controller#1001]
Despite I Exposed port 8080 in my docker file (and I exposed **only** 8080), Deis created a service for my app pointing port 80 to container port 5000, I don't know where the 5000 came from...
The app only worked when I changed Dockerfile + app to work on port 5000...

Regads

**Comment by bacongobbler** [comment]
@felipejfc was this a `git push` app or a private docker image pulled in with `deis registry:set` and `deis pull`? If it's the latter it is intended that you specify the port via `deis config:set PORT=8080` because we do not fetch the image and inspect it ourselves, and 5000 is the default port.

**Comment by felipejfc** [comment]
@bacongobbler It was a git push using Deis configured to use ECR as registry, maybe this case has a bug? (push with ecr as registry)

**Comment by bacongobbler** [comment]
yes, @helgi is aware of this bug. The private registry feature failed to cause the deploy to fail when PORT was not found in the environment. `deis config:set PORT=8080` should fix your issue for now.

**Comment by felipejfc** [comment]
ok, thanks!

**Comment by helgi** [comment]
https://github.com/deis/controller/pull/988 has the fix that would prevent you from doing a push / pull until the `PORT` has been set.

Going to close this one sine #988 takes care of the information side of things and should have made things self explaining :-) Reopen if you think there is more to this.
