### ISSUE TITLE
Scaling after rollback causes the controller to scale latest version

### ISSUE THREAD

**Issue by jeroenvisser101** [deis/controller#1012]
```
Deis Workflow 2.4.1 with k8s deployments on
Kubernetes 1.3.5
App has 2 process types, web and worker
```

We had some issues yesterday with a deploy that would not roll out correctly, and it was automatically rolled back by the controller. Today, I had 3 pods misbehaving and I scaled to 7 and then to 10 to rotate out the bad pods and it seems to have deployed the latest version instead.

It might be worth to note that this rollback only rolled back the `web` process, and the worker processes kept running the newer version. That might already be a bug on itself (although not an since no change was made in the worker's code on our side).

**Comment by helgi** [comment]
Which workflow version is that setup running?

**Comment by helgi** [comment]
Oh Nevermind, I read too fast and missed the top

**Comment by helgi** [comment]
Could you put describe of the deployment for web and the last 2 replicasets? 

Could you tell me a bit more about what you were seeing when it was having problems rolling out?

**Comment by jeroenvisser101** [comment]
hey @helgi, we had some issues with rollouts because we had a faulty node that was having DNS issues and kubelet wasn't able to pull the slugrunner images. That caused the rollback. I'll reach you on slack for the describes.

**Comment by jeroenvisser101** [comment]
Describes had no events, so no much info from there.

**Comment by helgi** [comment]
@jeroenvisser101 If you have the capacity and are able to reproduce your situation then it would be awesome if you could try out this branch https://github.com/deis/controller/pull/1029

**Comment by jeroenvisser101** [comment]
@helgi that could be hard, since the exact issue would require the kube master to be unavailable (which hasn't been since we moved from eu-west1-b to eu-west1-d). I'll see what I can do.

**Comment by jeroenvisser101** [comment]
@helgi I tried reproducing but couldn't, so let's hope your PR fixes it. If I'll ever come across it again, I'll let you know.
