### ISSUE TITLE
Port can be made optional for non-routable apps

### ISSUE THREAD

**Issue by kmala** [deis/controller#1015]
We error out if a port is not set for non-routable apps, but there might be scenarios where you might want to run an app as job which might not require any port.
we should still continue to check for ports even for non-routable apps because they might be private apps just servicing within the cluster but shouldn't error out if not set.

**Comment by helgi** [comment]
Are you talking about the `PORT` requirement we enforce when people have private registry?

**Comment by kmala** [comment]
no...if an app is set as non-routable using `deis routing` then there should be no mandatory check for port, it might be using private registry or public.

**Comment by helgi** [comment]
non-routable still means we create a Service, which requires a port. How do you propose we handle that scenario if we make the port optional? default port and the service won't really point at the app properly unless people adjust?

**Comment by felixbuenemann** [comment]
Couldn't it just skip creation of the service, if no PORT is set?

**Comment by kmala** [comment]
yes...i was thinking to leave it with the default port and update when deploy updates it.

**Comment by helgi** [comment]
We create the service when we create the namespace so we would have to change a few things around - it's done that way so you can add domains and more before a deploy. It's an assumption models make atm that they will have the service available to them
