### ISSUE TITLE
Internal server error when removing multiple keys of the same name

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/controller#1023]
Reported by @lzerma in deis/builder#416

<img width="448" alt="screenshot 2016-08-29 15 53 47" src="https://cloud.githubusercontent.com/assets/1020217/18055714/db2c04ac-6e00-11e6-9dff-5368f7fa83e0.png">

Stacktrace:

```
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 86, in destroy
    instance = self.get_object()
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 97, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 20, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 155, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
api.models.key.MultipleObjectsReturned: get() returned more than one Key -- it returned 7!
10.244.2.7 "DELETE /v2/keys/travis_ci HTTP/1.1" 500 25 "Deis Client vv2.4.0"
```

Looks like it shouldn't be too difficult to change delete to request an array of keys and delete all of them.

**Comment by helgi** [comment]
In the above scenario based on multi-delete for the same name (following what @Joshua-Anderson  said) then it would be rather hard as an end user to use the same email/identifier for various keys - Such as in the above example and what @jchauncey reported in #679 

So we have 3 options
1. go with the multi-delete above
2. disallow duplicate key names. Migration would prepend `-i++` like thing to each duplicate key. CLI would have to require a name
3. Same as above but CLI would not require a name and API does prepend behind the scenes

We may also want to consider showing a fingerprint in the CLI and thus the API response.

Thoughts?

**Comment by lzerma** [comment]
Hi @helgi, regarding the experience I had, it has used the same email/identifier once it is created on Travis CI using always the same parameters. 
e.g: 
```
ssh-keygen -t rsa -C travis_ci -N '' -f ~/.ssh/travis_ci
ssh-add ~/.ssh/travis_ci
./deis keys:add ~/.ssh/travis_ci.pub
# do whatever need to do
./deis keys:remove travis_ci
```
So, in this case, we do will have many keys with the identifier, but due a bug on the block above it wasn't removing...

**Comment by bacongobbler** [comment]
In the future I'd go with option 2 to disallow adding more than one key with the same comment identifier. If we could change the comment identifier before we upload so that we don't have to change the SSH key's comment any time we want to upload, that'd be great.

**Comment by helgi** [comment]
Whichever option we go with we should not modify the key - option 2 sounds reasonable all in all, but if you look at what happened to @jchauncey on the other tickst then it was two keys with his computers user@hostname so that could happen, tho it should be identical keys when that happens, I hope

**Comment by Joshua-Anderson** [comment]
Maybe instead of using the key comment as the name we have people give a name when uploading the key?

**Comment by helgi** [comment]
@Joshua-Anderson Yeah that is another way and is kinda what option 2 is about. The `CLI` is the one that passes on the name, the Controller does nothing with the key (which oddly enough is opposite of what we do with certs :P)

My reservation with requiring a key up front is the nice flow @lzerma showed above - One idea is to combine Option 2 and make the CLI smarter. When it gets a `409` it grabs what it considers the name and `appends` a `-i++` kind of thing and proposes that as a name to the user, allowing them to say `y/n` and optionally modify. That makes the current UX stick with a nicer smartness (am a bit inspired by seeing DNF in action recently), and we could have name as an option argument (oppose to a flag I suppose)

Trying to come up with a nice solutions while still solving the problem for @lzerma and others that may already have duplicate names in there.

Do you think that's achievable @Joshua-Anderson ?

**Comment by bacongobbler** [comment]
Could use the SSH fingerprint for identification rather than the comment, though then we're breaking API compatibility.

**Comment by helgi** [comment]
Yeah, would prefer not to break it anymore than making the name unique and the CLI already has to pass that in so the API would stay pretty much the same
