### ISSUE TITLE
Configured health checks don't appear with deis healthchecks:set

### ISSUE THREAD

**Issue by seanknox** [deis/controller#1030]
Running controller v2.4.2:

```
$ deis healthchecks:set liveness httpGet 3000 --type web --path users/sign_in -a perftest
Applying livenessProbe healthcheck... done

=== perftest Healthchecks

web:
--- Liveness
Initial Delay (seconds): 50
Timeout (seconds): 50
Period (seconds): 10
Success Threshold: 1
Failure Threshold: 3
Exec Probe: N/A
HTTP GET Probe: Path="users/sign_in" Port=3000 HTTPHeaders=[]
TCP Socket Probe: N/A

--- Readiness
Initial Delay (seconds): 50
Timeout (seconds): 50
Period (seconds): 10
Success Threshold: 1
Failure Threshold: 3
Exec Probe: N/A
HTTP GET Probe: Path="users/sign_in" Port=3000 HTTPHeaders=[]
TCP Socket Probe: N/A

$ deis healthchecks:list -a perftest                                     
=== perftest Healthchecks

web/cmd:
--- Liveness
No liveness probe configured.

--- Readiness
No readiness probe configured.
```

**Comment by helgi** [comment]
From conversation on Slack - @kmala pointed out this is intended behaviour but I made this point

> makes me wonder if `list` without proc type should just list out all proc types (either with or without the health info)

We could use this as a ticket to potentially improve the UX if we can get to an agreement on what `list` should look like without the proc type arg

**Comment by bacongobbler** [comment]
Note that this is a common issue: deis/deis#5092

Perhaps there's some documentation that we need to update as well here so users aren't confused. I agree that this is a problem as it is technically a breaking change.

**Comment by helgi** [comment]
Think we can just start outputting info when there is no proc type defined and call it a day - some docs is probably in order

**Comment by kmala** [comment]
do you mean all the healthchecks info?

**Comment by helgi** [comment]
Yeah, see my original comment on this ticket - show all proc types, potentially leave out health info, or just include it and that's just the "show me all" view, and then if you want a per proc type view you specify the proc type.

**Comment by kmala** [comment]
config doesn't have info about all the proctypes, it only knows those which have healthcheks..so for showing all proctypes we need to make more changes

**Comment by helgi** [comment]
Oh sorry yeah I meant all that have been set, beyond that I don't think we should show proc types that have no gotten things set on them.
