### ISSUE TITLE
Logs API returns weird string

### ISSUE THREAD

**Issue by olalonde** [deis/controller#1033]
When GETting the logs, I'm seeing a long string with an unusual encoding

```
b'some long string with escaped new lines (\n)'
```

Would it be possible instead to return text/plain logs? I'm not sure how to decode the current format in JavaScript for https://github.com/olalonde/deisdash

**Comment by helgi** [comment]
That's a binary string from python - should be internally converted to string but are you requesting it as text instead of json?

What workflow version are you on?

**Comment by olalonde** [comment]
workflow v2.4.1. "That's a binary string from python", I figured this through Google but afaict, it's not designed to be an "over the wire" format and I'm not sure there are any Javascript decoders for it. Looks like the workflow cli just replaces `\n` with new lines but that's not ideal either (https://github.com/deis/workflow-cli/blob/master/cmd/apps.go#L180).

**Comment by helgi** [comment]
Yeah it's not over the wire, we have (in the past anyway) returned it as non-binary string, tho I saw https://github.com/deis/controller-sdk-go/blob/master/apps/apps.go#L110 so I need some answers from @Joshua-Anderson or someone that worked on the SDK on what that is supposed to be chopping off.

The newline stuff, I think that might be a go situation but I'm not sure.

In the controller we specifically tell it to be text/plain so something is funky... https://github.com/deis/controller/blob/master/rootfs/api/views.py#L220-L224

**Comment by Joshua-Anderson** [comment]
@olalonde the splitting over the `\n` is because golang doesn't parse the http response string for escape characters. Since the CLI needs to split on newlines to color the output regardless, it doesn't really make sense to parse them.

As for why we're chopping off the `b'` and then the `'`, when @jchauncey redid the logging system, he noticed this output and simply chopped it off.

Ideally we find the source of this in the controller and return a plain string, like you expected.

**Comment by olalonde** [comment]
FWIW I reported a similar issue in deis v1 (https://github.com/deis/deis/issues/4657), at the time it was needlessly returning a massive JSON string. Hope it will be really fixed this time :) Just plain text  makes it easier to write third party clients.

**Comment by helgi** [comment]
@olalonde Plain text was always the plan, since we even return text/plain content type :) This got messed up in a Python 3 move and the SDK / CLI simply chopping those bits off instead of trying to solve it up in the API.

**Comment by olalonde** [comment]
Yeah I understand, good job on the awesome work on Deis btw, all of you :)
