### ISSUE TITLE
deis tls:enable set true but not enabled

### ISSUE THREAD

**Issue by vdice** [deis/controller#1047]
When I set `deis tls:enable -a bar` where my `bar` app is a stock [example-dockerfile-python](https://github.com/deis/example-dockerfile-python) app, I see that the controller claims it is set but both the annotations differ as well as I do not see redirects when I curl the app root URL:
```
$ deis tls:enable -a bar
Enabling https-only requests for bar… done
$ deis tls
=== bar TLS
HTTPS Enforced: true
$ curl -sL -w "%{http_code}\\n" bar.104.198.54.147.nip.io -o /dev/null
200
$ k get svc --namespace=bar bar -o json | jq -r '.metadata.annotations'
{
  "router.deis.io/domains": "bar",
  "router.deis.io/maintenance": "False",
  "router.deis.io/ssl.enforce": "False",
  "router.deis.io/whitelist": ""
}
```

(On gke 1.3.6 w/ workflow-v2.5.0 (as of https://github.com/deis/charts/pull/348/commits/cbcfd646b71bf1902c81ad44121b42dff9c6c27b) and cli version v2.5.1, using off-cluster (gcr) registry and (gcs) object storage)

**Comment by bacongobbler** [comment]
I cannot reproduce on my cluster:

```
><> deis apps
=== Apps
foo
go
><> deis tls -a go
=== go TLS
HTTPS Enforced: false
><> deis tls:enable -a go
Enabling https-only requests for go... done
><> curl go.k8s.local
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.2</center>
</body>
</html>
><> k --namespace=go get svc go -o yaml | grep enforce
    router.deis.io/ssl.enforce: "True"
```

Let's take this offline and see if we can debug together. :)

**Comment by bacongobbler** [comment]
Actually @vdice would you mind posting your controller logs so we can get a repro on how you got into this state? Perhaps there's an edge case I'm missing.

**Comment by vdice** [comment]
Fixed by https://github.com/deis/controller/pull/1048
