### ISSUE TITLE
[Feature Request] Being able to set tls:enable as default for new apps

### ISSUE THREAD

**Issue by felipejfc** [deis/controller#1052]
This way when working with teams, one could enable tls only mode by defalt, "forcing" other teams to use ssl by default but keeping the option not to use.

**Comment by bacongobbler** [comment]
This sounds like a good use case for https://github.com/deis/deis/issues/1804.

**Comment by helgi** [comment]
https://github.com/deis/controller/issues/383 Captures very similar things as well

**Comment by helgi** [comment]
I'm going to close this ticket since #383 is really the master ticket on this. This ticket is already linked to that ticket via the GH interface so we won't have lost track of this!

Thanks for the suggestions :)
