### ISSUE TITLE
Proposal: Add Release Data to Pod Environment

### ISSUE THREAD

**Issue by felixbuenemann** [deis/controller#1057]
It would be great if DEIS could add some environment variables with release information to the pods environment.

Currently only `WORKFLOW_RELEASE=v123` is set, but for things like release and error tracking the commit hash would be very useful.

Heroku Labs has a similar feature called [Dyno Metadata](https://devcenter.heroku.com/articles/dyno-metadata).

We could have a few additional `WORKFLOW_*` environment vars:

* `WORKFLOW_RELEASE=v88` (already exists)
* `WORKFLOW_RELEASE_CREATED_AT=2016-09-12T00:08:22Z`
* `WORKFLOW_RELEASE_DESCRIPTION="gitlab-runner deployed 5c2d30d"`
* `WORKFLOW_RELEASE_HASH=5c2d30d6719413ce7d5f5fc7a66d8c349dce162b`

The WORKFLOW_RELEASE_HASH could use the GIT commit SHA for Buildpack or Dockerfile builds and the Docker Image ID when pulling images.

The important thing about `WORKFLOW_RELEASE_HASH` is that it should be able to be determined outside of DEIS based on the pushed data, e.g. in a CI system one might have these stages:

* Push git ref to DEIS Workflow
* Create a release with same git ref in error monitoring tool (eg. Sentry)
* Push source code / source maps to Sentry

Currently to achieve the same one would have to either grab the release version number from the git push logs to pass it on to the other stages or query deis for the last release version, which is prone to race conditions.

If the ambiguos value for `WORKFLOW_RELEASE_HASH` is a problem, this variable could be omitted for Docker image deploys and instead replaced with `WORKFLOW_RELEASE_COMMIT` or `SOURCE_VERSION` (like during build) for Buildpack and Dockerfile deploys, because an equivalent value can easily be baked into a Docker image.

This is somewhat related to deis/builder#418 which introduced the `SOURCE_VERSION` environment variable at build time.

**Comment by bacongobbler** [comment]
This sounds like a great enhancement and an easy task to do if someone wants to get their hands dirty. We inject environment variables into the pods [here](https://github.com/deis/controller/blob/91abc2d723ab541568d40c5261a440b7a901799e/rootfs/api/models/app.py#L918-L922), so adding these in shouldn't be too hard using the available build attributes.
