### ISSUE TITLE
Being able to create k8s internal service to custom process types

### ISSUE THREAD

**Issue by felipejfc** [deis/controller#1063]
The use case is the following, I have an app that I want to put behind a [oauth2_proxy](https://github.com/bitly/oauth2_proxy), I wanted it to work this way:

I create an app in Deis, e.g. my-app
I have 2 process types in my-app, **cmd**: running oauth2_proxy and **backend**: running the app itself

If it was possible to have an internal k8s service for backend process, I would be able to expose *cmd* normally and proxy requests from **cmd** to **backend** internally.

Is it possible today? If not, I think that it would be a nice feature to add.

regards

**Comment by helgi** [comment]
We had looked at that and decided each application would get a service but not the various process types within the application.

You'd have to split this into 2 apps and use `routing:disable` to keep one of them from the public

**Comment by felipejfc** [comment]
I see, what a pity then, I think it would be cleaner to have all my app's components contained only in one app
Can't this be reconsidered? Is there any strong technical reason for not doing this?

**Comment by helgi** [comment]
@felipejfc One of the problems is do we create a service for *all* process types or not? Which then turns into do you have enough IPs available to you to support that? 

Do we make it an opt-in for non-web/cmd (the ones that get a Service for now) to get past the IP problem mentioned above. This could be a viable option but is a complication as well

**Comment by felipejfc** [comment]
I think that a opt-in would be awesome, because it is not an essential feature in most of the cases but can be VERY handy in some others... We're using Deis for 1 month now and already hitted this issue twice, for now we are solving the problem running 2 processes inside the same container (because we didn't wanted to create 2 apps), but running 2 processes within the same container is dirty too... 

Doesn't sound like something so hard to implement I think I could try to make a PR here if you guys agree and maybe give a little direction.

**Comment by helgi** [comment]
@felipejfc If you want to try it then that's great! But any functionality that has to do with process types is inherently more complicated than at first blush since you need to handle internal data much differently.

This would involve changes to the Controller, the SDK and CLI

What is the downside of creating 2 apps to solve for this? Additional images created and such management problems?

**Comment by helgi** [comment]
Here are two tickets worth reading: https://github.com/deis/controller/issues/883 and https://github.com/deis/controller/issues/656

**Comment by felipejfc** [comment]
Having to deal with 2 apps instead of one, 2 deploys instead of one, and most a question of principles, I guess. I'm not confortable with having to split the same app's components in two apps.
----

Hmm, I see, the port's question is really something that we would need to deal with. I don't like the solution of just opening all ports because of security... but maybe leaving this decision to the user would be enough. I'll give it some thinking and will close this issue for now, if I come with something good I'll reopen it. Thanks!

**Comment by helgi** [comment]
@felipejfc Sounds good! Thanks for understanding. If we get past a few of these hurdles then it would probably be viable.
