### ISSUE TITLE
Move parts of the code base to be statically typed

### ISSUE THREAD

**Issue by helgi** [deis/controller#1069]
Since Python 3.5 it has been possible to annotate functions with static typing. Python however does not enforce that but http://mypy-lang.org/ can be used to do linting.

This could be useful for `scheduler` and various utils we have around. MyPy might not support all the various functionalities we use but a recent release added async in so there is hope!

It would be interesting to explore the feasibility of this - Especially since we can easily mix and max static and dynamic types

**Comment by bacongobbler** [comment]
I think the effort to improve the codebase would be better spent rewriting the controller entirely in Go. Closing as a wontfix.
