### ISSUE TITLE
remove double ISO 8601 datetime format variables

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#1084]
We have two references to ISO 8601 datetime formats in the code:

 - https://github.com/deis/controller/blob/ad182b24d00f1fa5ee212dfa27a2157acac27524/rootfs/api/settings/production.py#L144
 - https://github.com/deis/controller/blob/ad182b24d00f1fa5ee212dfa27a2157acac27524/rootfs/scheduler/__init__.py#L37

These datetimes are shared amongst both packages and should be refactored out somewhere it can be used by both packages.

**Comment by helgi** [comment]
That's intentional and was changed recently - I am trying to not have django settings used in the scheduler so I don't want to consolidate this again.

**Comment by bacongobbler** [comment]
That's fine, I'm just looking at it from a maintenance perspective. With this change in place we now have to maintain two locations for the datetime format, which may or may not be a hassle down the road. For example if we add a third django package that ships logs to the logger for an application, we'll have to re-define DATETIME_FORMAT again.

**Comment by helgi** [comment]
I'm confused - the settings file still has its setting for date time and would be used by a 3rd party package if we included it.

The scheduler is defining kubernetes date format where as the main settings file is all about defining what django needs. 

From my perspective the current setup is a better for maintenance
