### ISSUE TITLE
deis apps:destroy should delete app even if namespace has been deleted

### ISSUE THREAD

**Issue by jchauncey** [deis/controller#1100]
I deleted an apps namespace by accident and now I cant delete the app from deis:

```
╰─± deis destroy -a artful-vacation
 !    WARNING: Potentially Destructive Action
 !    This command will destroy the application: artful-vacation
 !    To proceed, type "artful-vacation" or re-run this command with --confirm=artful-vacation

> artful-vacation
Destroying artful-vacation...
Error: Unknown Error (503): {"detail":"Could not delete Kubernetes Namespace artful-vacation"}
```

**Comment by bacongobbler** [comment]
+1, this has burned me a few times as well.

For reference we allowed apps to be deleted [even if the etcd keyspace was deleted](https://github.com/deis/deis/blob/4ade01607b1cbe9c583e6491fd4cd3b8b9599a65/controller/api/models.py#L1148-L1151) in v1.

**Comment by helgi** [comment]
I'll grab this now - shouldn't be much work

**Comment by helgi** [comment]
@jchauncey oh, did you check if the Namespace was still around?  Based on your comment you did delete it from undernearth Deis.That particular error means it was not deleted within the allocated 30 seconds. `DELETE` is ran and then we wait 30 seconds

I can change this so we first check if it exists before `DELETE` and then return so it doesn't even go into that cycle.
