### ISSUE TITLE
Existing app processes killed when using "deis pull" in directory without Procfile

### ISSUE THREAD

**Issue by seanknox** [deis/controller#1123]
(Not sure if this is a https://github.com/deis/workflow-cli or controller issue—let me know if I should file there instead)

STR: 
- Deploy an Docker-based app that has a `Procfile`
- Once running, cd out of directory with `Procfile`
- Deploy an image w/Procfile from a remote registry using `deis pull quay.io/... -a $APP`

EXPECTED:
- New pods spun up in rolling update via deployment
- Old pods terminated after new pods pass readiness checks

ACTUAL:
- All existing app pods are killed (no running processes)
- Unable to scale processes; `deis ps:scale` returns 404s

WORKAROUND:
1. `cd` to directory with `Procfile`
2. run `deis pull` again
3. manually scale app processes with `deis ps:scale`

```
$ deis version
v2.7.0
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4+3b417cc", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"not a git tree", BuildDate:"2016-10-21T22:34:07Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3+coreos.0", GitCommit:"7819c84f25e8c661321ee80d6b9fa5f4ff06676f", GitTreeState:"clean", BuildDate:"2016-10-17T21:19:17Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

## `deis pull` from outside of the repo--kills all processes

```
INFO [acceptance]: scaling Deployment acceptance-worker from 1 to 0 replicas
INFO:scheduler:[acceptance]: scaling Deployment acceptance-worker from 1 to 0 replicas
INFO [acceptance]: Not scaling Deployment acceptance-cron to 0 replicas. Already at desired replicas
INFO:scheduler:[acceptance]: Not scaling Deployment acceptance-cron to 0 replicas. Already at desired replicas
INFO [acceptance]: scaling Deployment acceptance-web from 1 to 0 replicas
INFO:scheduler:[acceptance]: scaling Deployment acceptance-web from 1 to 0 replicas
INFO [acceptance]: admin scaled pods worker=0 cron=0 web=0
INFO:api.models.app:[acceptance]: admin scaled pods worker=0 cron=0 web=0
INFO [acceptance]: build acceptance-5aaa891 created
INFO:api.models.app:[acceptance]: build acceptance-5aaa891 created
INFO [acceptance]: admin deployed quay.io/my_org/rails_app:508eead72deb25b8e187cb691b06a0e5e6777124
INFO:api.models.app:[acceptance]: admin deployed quay.io/my_org/rails_app:508eead72deb25b8e187cb691b06a0e5e6777124
INFO [acceptance]: quay.io/my_org/rails_app:508eead72deb25b8e187cb691b06a0e5e6777124 exists in the target registry. Using image for release 383 of app acceptance
INFO:api.models.app:[acceptance]: quay.io/my_org/rails_app:508eead72deb25b8e187cb691b06a0e5e6777124 exists in the target registry. Using image for release 383 of app acceptance
```

## no processes remain
```
$ deis ps -a acceptance
=== acceptance Processes
$
```

## switch to repo, 404s when trying to scale

```
$ deis ps:scale web=1 worker=1  -a acceptance                                                                                
Scaling processes... but first, coffee!
Error: Not Found
```

## pull from the repo to fix 

```
$ deis pull quay.io/my_org/rails_app:508eead72deb25b8e187cb691b06a0e5e6777124 -a acceptance                                  
Creating build... done
```

## scaling processes manually then works

```
$ deis ps:scale web=1 worker=1  -a acceptance                                                                                 
Scaling processes... but first, coffee!
done in 46s
=== acceptance Processes
--- web:
acceptance-web-1736370019-wij47 up (v384)
--- worker:
acceptance-worker-3840768182-msfdi up (v384)
```

**Comment by bacongobbler** [comment]
This is a duplicate of https://github.com/deis/controller/issues/1062. You can try the feature flag proposed at https://github.com/deis/controller/pull/1099 but this is intentional by design.

Since this is the second time this has occurred, I'm prone to deprecating `deis pull` reading a Procfile from the local directory as this has been causing too many headaches for people.

**Comment by seanknox** [comment]
> Since this is the second time this has occurred, I'm prone to deprecating the feature that allows deis pull to read a Procfile from the local directory as this has been causing too many headaches for people.

I *think* I'm onboard with that. My expectations around a local `Procfile` are deeply set from years of foreman/Heroku use—and looks like I'm not the only one. I'll close this and take a look at the other PRs you referenced. Thanks!
