### ISSUE TITLE
Process type names should allow underscore

### ISSUE THREAD

**Issue by ineu** [deis/controller#1124]
Despite Heroku [states](https://devcenter.heroku.com/articles/procfile#declaring-process-types) that process names should be alphanumeric, they allow underscore in process names as well. Deis Workflow should also allow underscore to keep compatibility with both Heroku and Deis 1, which also supports underscores.

**Comment by kmala** [comment]
Ohh, i wasn't aware that heroku supports that even though saying alphanumeric.
Even deis v1 had that check on the proctype https://github.com/deis/deis/blob/e5f349dd9fb090aa993ad74758b3bbf038d44d23/controller/api/serializers.py#L19 but only thing is that it is not checked at all places.

**Comment by bacongobbler** [comment]
I just tested on Heroku to verify and it is indeed true:

```
><> l
Godeps  LICENSE  Procfile  README.md  web.go
><> vim Procfile 
><> git add Procfile 
><> git ci
[master 374ad91] add underscores
 1 file changed, 1 insertion(+)
><> git push heroku master
Counting objects: 99, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (57/57), done.
Writing objects: 100% (99/99), 22.52 KiB | 0 bytes/s, done.
Total 99 (delta 36), reused 96 (delta 36)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Go app detected
remote: -----> Checking Godeps/Godeps.json file.
remote: -----> Installing go1.6.3... done
remote: -----> Running: go install -v -tags heroku . 
remote: github.com/deis/example-go
remote: -----> Discovering process types
remote:        Procfile declares types -> web, worker_underscores
remote: 
remote: -----> Compressing...
remote:        Done: 2.2M
remote: -----> Launching...
remote:        Released v3
remote:        https://floating-escarpment-10162.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/floating-escarpment-10162.git
 * [new branch]      master -> master
><> cat Procfile 
web: example-go
worker_underscores: echo hi
><> heroku scale worker_underscores=1
Scaling dynos... done, now running worker_underscores at 1:Free
><> heroku ps
=== web (Free): example-go (1)
web.1: up 2016/10/28 10:09:22 -0700 (~ 36s ago)

=== worker_underscores (Free): echo hi (1)
worker_underscores.1: crashed 2016/10/28 10:09:41 -0700 (~ 17s ago)
```

**Comment by ineu** [comment]
We rely much on this behaviour in current clusters running Deis 1. For example, it's convenient to run different queues of background job processor (Sidekiq in our case) as different process types.

**Comment by bacongobbler** [comment]
There's nothing stopping you from using dashes in the current implementation (e.g. `worker-sidekiq`). Yes, we can look into getting underscores working on v2.

**Comment by ineu** [comment]
@bacongobbler Unfortunately, dashes aren't allowed as well: https://github.com/deis/controller/blob/master/rootfs/api/serializers.py#L21

Here's the test with DW v2.7:
```
> $ cat Procfile
foo-bar: rackup
> $ git push deis
...
Build complete.
Launching App...
remote: 2016/10/29 07:47:17 Error running git receive hook [publishing release (Unknown Error (400): {"procfile":["Process types can only contain alphanumeric"]})]
...
```

**Comment by ineu** [comment]
Deis 1 also allows uppercase letters, So validation should read:
```python
PROCTYPE_MATCH = re.compile(r'^(?P<type>[a-zA-Z0-9_]+)$')
```

**Comment by bacongobbler** [comment]
We're not going to support underscores in process types but dashes and capitals are fine.

**Comment by ineu** [comment]
No compatibility with Heroku and Deis 1 then?

**Comment by bacongobbler** [comment]
Given that handling underscores are fraught with edge cases in kubernetes since they don't support them, I would say uppercase, lowercase, numerical and dashes are acceptable.

**Comment by bacongobbler** [comment]
If you feel like adding underscores, feel free to take a crack at it though.

**Comment by ineu** [comment]
I wasn't aware K8S doesn't like them. In that case dashes are just as fine.
