### ISSUE TITLE
swap out raw http requests for the scheduler with a kubernetes client lib

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#1128]
A lot of the code in the scheduler is [raw HTTP requests](https://github.com/deis/controller/blob/d24d628affd3fb8e1a768e6ab079ec60a804ebe0/rootfs/scheduler/resources/deployment.py#L25-L29), retries and error code catching. It would be better to either abstract this and utilize a kubernetes client library, contribute a lot of the code upstream to a client lib or create one ourselves.

This would allow us to test a lot of the kubernetes interactions in the scheduler code outside of the scope of the controller and improve portability/readability.

**Comment by jgmize** [comment]
https://github.com/kelproject/pykube may be of use for this.

**Comment by helgi** [comment]
The scheduler is already isolated from the rest of the Controller if you don't include `django.cache` and a lil bit of `django.settings` in the tests and `from api import __version__ as deis_version` in the main scheduler but all of those are easy enough to remove

Any library you move to you still have to do error handling - Abstracting the code you pointed to for example could easily be moved *into* `http_get` and use a bubble up exception model

**Comment by bacongobbler** [comment]
After attempting this over a few hours (overnight + today), the amount of code required to rewrite is too great to tackle a change this large for a couple reasons:

 - Way too much leftover cruft from the ReplicationController -> Deployment refactor
 - The `scheduler` module is over 5,000 LOC, and the `api/models` package is 3,000 LOC
 - Too many intricacies in the `scheduler` module that are untested and undocumented, making changes to that package fraught with bugs
 - It touches every aspect of the scheduler so we would have to re-test *everything* when cutting the release.

And the biggest point:

 - The existing code already works as-is. This was merely an experiment to make the code more readable and more approachable to contributors.

When I gave up, I was already at 6,000 LOC, including a refactor of the entire `scheduler` package.

My suggestion would be that we should completely rethink and rewrite the API server in Go before trying to invest this much effort into the component.

**Comment by bacongobbler** [comment]
However thank you for the pointer @jgmize. pykube was a breeze to work with. I initially attempted with https://github.com/kubernetes-incubator/client-python/ but soon found that to be a terrible library to work with and went with pykube instead. That library could very well be the benchmark on how to write **good** software.
