### ISSUE TITLE
OpenSSL.SSL.Error on booting

### ISSUE THREAD

**Issue by monaka** [deis/controller#1185]
I re-installed my Workflow to v2.9.1 after deleting v2.4.0 by `kubectl delete ns deis`.
some values extracted by `helm inspect values deis/workflow | sed -n '1!p' > values.yaml` are modified.
And I deployed Deis by calling `helm install deis/workflow --namespace deis -f values.yaml`

Database migration looks done with success. But I got an exception from Django.
The log is https://gist.github.com/monaka/317b5e812bb10337301896f37d2ef2f7

Even though this error, Controller is keep running. Builder is also running but '0/1' ready. Router is under CrashLoopBackOff.

Where is the checkpoint against this issue?

**Comment by monaka** [comment]
Additional information. My K8s API endpoint is encrypted with self signed certs.

**Comment by monaka** [comment]
Conrtoller expects `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` available. But there have no ca.crt on my K8s. It seems to be caused my misconfiguration. Close this by myself.

**Comment by monaka** [comment]
I got still an error after adding ca.crt. I guess this is caused SSL verification.
Can I make skip verification steps? like

```
context.verify_mode = ssl.CERT_NONE
context.check_hostname = False
```

Or can I set URL to API server using an environment variable or something?

```
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 392, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: []
```

**Comment by bacongobbler** [comment]
it's not in a release yet, but https://github.com/deis/controller/pull/1158 will enable that.

**Comment by monaka** [comment]
@bacongobbler I see. #1158 is it to me. I'll build Controller image with the master branch and continue  upgrading.
Thank you for your support.

**Comment by monaka** [comment]
I pulled `quay.io/deis/controller:git-184b54c` image and run with `K8S_API_VERIFY_TLS` `"false".
It worked well.
I see it should be regenerated my CA later. Thanks.
