### ISSUE TITLE
Re-enable TLS verification in Azure ACS quickstart

### ISSUE THREAD

**Issue by slack** [deis/controller#1193]
Azure ACS currently generates invalid TLS certificates when standing up Kubernetes. Fixes have been pushed to `acsengine` as well as the internal deployment system. Once those changes reach ACS production the quickstart for Azure ACS should re-enable TLS verification.

This is the commit that added `controller.k8s_api_verify_tls=false` to the quickstart:
https://github.com/deis/workflow/pull/640/commits/1fb84dc4a95737ceb9e7f4f1ced22aaac84fc298

**Comment by mboersma** [comment]
@slack do you know if Azure ACS has the aforementioned fixes in production yet?

**Comment by slack** [comment]
Yes, looks like the updates finished shipping last week. I haven't had time to manually test though.

**Comment by dtzar** [comment]
I just deployed removing the verification on a fresh run through a new cluster creation and everything is running well.

**Comment by mboersma** [comment]
Closed by deis/workflow#716. Thanks again @dtzar!
