### ISSUE TITLE
Integrate letsencrypt into the app provisioning / installation process

### ISSUE THREAD

**Issue by deis-admin** [deis/controller#1222]
_From @landonclark on October 28, 2015 16:55_

With [Let's Encrypt](https://letsencrypt.org) heading into Beta recently, it would be great for every http endpoint in Deis to be TLS enabled by default (over-rideable of course per app if you want to use an EV cert).

This would solve a lot of (minor!) issues - 
1. Bootstrapping the first user in a Deis cluster over HTTP.
2. Requiring a wildcard certificate.
3. Enabling better URLs even when a wildcard cert is enabled.  For instance, I dedicated *.apps.example.com to Deis, but I want to deploy to blog.example.com. 

_Copied from original issue: deis/deis#4681_

**Comment by deis-admin** [comment]
_From @krancour on October 28, 2015 17:51_

This has been discussed internally and the consensus is that we'll be looking to nail this right out of the gate with v2, but no changes of this magnitude will be making it into the v1.x.  Assigning v2 as he milestone.

**Comment by deis-admin** [comment]
_From @almereyda on December 5, 2015 20:33_

I don't know how much the dokku and deis development are already synced, but there is a letsencrypt plugin for the first at https://github.com/sgulseth/dokku-letsencrypt.

**Comment by deis-admin** [comment]
_From @slack on June 3, 2016 21:53_

Keeping this as an enhancement request, but unscheduling from the 2.0 milestone.

**Comment by deis-admin** [comment]
_From @jgmize on June 7, 2016 5:16_

There was a demo of [kube-lego](https://github.com/jetstack/kube-lego) at [last week's Kubernetes community meeting](https://www.youtube.com/watch?v=M3b8Wzqi56A) that looked like it could be relevant to this issue.

**Comment by deis-admin** [comment]
_From @bourquep on December 14, 2016 1:29_

The [kube-cert-manager](https://github.com/PalmStoneGames/kube-cert-manager) project might also be useful/relevant.

**Comment by bacongobbler** [comment]
closing in favour of https://github.com/deis/workflow/issues/708.
