### ISSUE TITLE
PGPORT is not adhered to for tests

### ISSUE THREAD

**Issue by robholland** [deis/controller#1229]
Contrary to the README/Makefile setting PGPORT makes no difference, port 5432 is always used. Please update the README/Makefile or better, allow PGPORT to work so postgres can be run on any port.

**Comment by bacongobbler** [comment]
Can you point to where it says PGPORT? The correct port envvar is [DEIS_DATABASE_SERVICE_PORT](https://github.com/deis/controller/blob/master/rootfs/api/settings/production.py#L345).

**Comment by bacongobbler** [comment]
Ah I see what you mean. I'll be happy to update those.
