### ISSUE TITLE
Controller logs should include timestamps

### ISSUE THREAD

**Issue by ineu** [deis/controller#1256]
At the moment controller logs don't include timestamps which makes them not very helpful. This is not an issue if docker is configured to log to journald, but if it is configured with the `json-file` driver, then log entries fetched by `docker logs` or `kubectl logs` don't include any timestamps. 
Thus controller logs (builder's logs also have this problem) should include timestamp, just like the `router` or `registry` do.
I'm using Controller v2.11.0.

**Comment by bacongobbler** [comment]
If you're fetching the logs you can use the `--timestamps` option flag like `kubectl -n deis logs --timestamps <deis-controller-pod>`. Kubectl hides timestamps by default for whatever reason.

**Comment by ineu** [comment]
@bacongobbler That works. `docker logs` still doesn't show timestamps, but it doesn't matter with the `kubectl --timestamps`. Thank you.
