### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ineu** [deis/controller#1294]
On deis workflow 2.14.0 I see the following in the controller's logs:
https://gist.github.com/ineu/698680906dca84950963df5f2e3e507c
Nothing interesting in the builder's logs.

Must be a temporary failure because deploys work fine now. May be related to 2.14.0, I've never seen such issue in 2.11.0

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/controller#24
