### ISSUE TITLE
Improvement: display current number of processes in `deis ps`

### ISSUE THREAD

**Issue by ineu** [deis/controller#1295]
In Deis 1 processes were named like `type-number`, so you could take a look at the highest number to understand the current count. But in K8S pods have unique hashes instead of numbers, so it's not easy to tell what the current count is if you want to scale. So a nice improvement would be to display a count next to the process name, i.e.
```
=== foo Processes
--- web (10):
...
```

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/controller#23
