### ISSUE TITLE
deis autoscale with Error: Unknown Error (400)

### ISSUE THREAD

**Issue by gemoya** [deis/controller#1309]
Hi.

I think i have a problem with workflow and RBAC on kubernetes 1.6.6. When I try to apply an autoscale on an app I got 
```
Applying autoscale settings for process type web on lala... Error: Unknown Error (400): {"detail":"Expecting value: line 1 column 1 (char 0)"}
```
Inspecting deis-controller logs I have:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
ERROR:root:Expecting value: line 1 column 1 (char 0)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 185, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 20, in perform_create
    obj = serializer.save(owner=self.request.user)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 215, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 916, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/api/models/appsettings.py", line 187, in save
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Expecting value: line 1 column 1 (char 0)
```
Some idea how I can fix this ?

Cheers!

**Comment by vdice** [comment]
@gemoya could you send the particular autoscale commands used?  I was unable to reproduce this issue on Workflow 2.15.0 w/ RBAC, k8s 1.6.4 and simple `deis autoscale:list/set/unset` flow...

**Comment by gemoya** [comment]
@vdice 

Here is the outputs( app name is lala).

```
# deis autoscale:list -a lala
=== lala Autoscale

```
```
# deis autoscale:set web --min=1 --max=3 --cpu-percent=50 -a lala
Applying autoscale settings for process type web on lala... Error: Unknown Error (400): {"detail":"Expecting value: line 1 column 1 (char 0)"}
```

An additional question: Is the workflow's installation guide on https://deis.com/docs/workflow/installing-workflow/ with the service account and clusterbinding on helm complete? Are there more steps to do?

The first time I deployed deis + Kubernetes 1.6.6 with RBAC I got a lot of problems with the pods, so I used this https://gist.github.com/Bregor/66a4ce55a4d84b631419b81c7b97b5b9 . With this I was able to get the all pods running and creating/pushing apps. But no Autoscale.


Maybe I am doing something wrong ?

**Comment by vdice** [comment]
@gemoya Thank you for the commands and further info.  I believe the issue here is the use of the old gist from Bregor.  That was an initial draft of all RBAC permissions needed for Workflow; however, more were added to the pull requests (including autoscale) as errors (like this one) were discovered.  Therefore, the final version needed lies in the last release (first to support RBAC) of Workflow v2.15.

If you are in a position to do so, I would upgrade the existing Workflow release to `v2.15` and verify `deis autoscale` works as intended.  

For clarity/comparison, here are the steps I went through just now to verify working autoscale in v2.15: https://gist.github.com/vdice/0f383d7f957910242a130c95af725f8e

**Comment by gemoya** [comment]
@vdice 

Thanks for your help!. I was building my own RBAC clusterroles while I was trying to get deis working.

Your steps work, but the line 13:
https://gist.github.com/vdice/0f383d7f957910242a130c95af725f8e#file-gistfile1-txt-L13

must be 
```
helm install deis/workflow ...
```

Now I am doing stress tests to get the autoscale creating new pods.

**Comment by vdice** [comment]
@gemoya Is the cluster now healthy and running as expected w/ latest install?  If so, was going to close this issue.

**Comment by gemoya** [comment]
@vdice thanks for all guys!
