### ISSUE TITLE
Make slugrunner image configurable

### ISSUE THREAD

**Issue by technosophos** [deis/controller#135]
The image used by slugrunner should be configurable.

We need to make it possible for the slugrunner image to be configured by a cluster administrator so that any deploys use that slugrunner instead of the default Deis slugrunner.

**Comment by arschles** [comment]
@technosophos should deis/builder have the same capability with slugbuilder?

**Comment by technosophos** [comment]
Probably.

**Comment by smothiki** [comment]
Can you be more specific about what configs should be tunable

**Comment by technosophos** [comment]
I was initially imagining making `image` tunable for slugrunner. And @arschles is suggesting the same for slugbuilder. That was all.

**Comment by technosophos** [comment]
I think we can safely demote this from Beta, since none of the Beta requirements specify or rely upon this behavior.

**Comment by helgi** [comment]
This has not been fixed. The PR in question does slug and docker builder, not slug runner

https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L31 is still around

**Comment by krancour** [comment]
> I think we can safely demote this from Beta, since none of the Beta requirements specify or rely upon this behavior.

I would argue for including this.  Once we transition to immutable tags on our images, we're not going to want to be figuring out a way to insert the latest tag for slugrunner and slugbuilder into controller and builder... we'll be wanting to insert it into env variables in the manifests for those components instead.

**Comment by helgi** [comment]
Fixed by #515
