### ISSUE TITLE
Proposal: containerize the development environment

### ISSUE THREAD

**Issue by krancour** [deis/controller#18]
This is to lower the barrier to entry for hacking on Deis while also standardizing the development environment for all contributors.

**Comment by Joshua-Anderson** [comment]
How would this work with postgres? Would the makefile *also* spin up a postgres container and connect the two together?

**Comment by bacongobbler** [comment]
@Joshua-Anderson didn't stop me :) https://github.com/deis/postgres/blob/master/contrib/ci/test-minio.sh

**Comment by bacongobbler** [comment]
specifically https://github.com/deis/postgres/blob/master/contrib/ci/test-minio.sh#L43-L44. We link postgres to minio using `docker run --link` and use that for testing minio compatibility.
