### ISSUE TITLE
Use k8s deployments?

### ISSUE THREAD

**Issue by krancour** [deis/controller#19]
Disclaimer: this is an alpha feature, but it looks interesting.  I think this could dramatically simplify some of what's in `scheduler/k8s.py` if it sticks around.

http://kubernetes.io/v1.1/docs/user-guide/deployments.html

**Comment by bacongobbler** [comment]
> Deployments is part of the extensions API Group and is not enabled by default.

Would be a neat opt-in feature.

**Comment by deis-admin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VKQHq9We&#x2F;1-use-kubernetes-deployments"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Use Kubernetes Deployments</a>

**Comment by slack** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VKQHq9We&#x2F;1-use-kubernetes-deployments"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Use Kubernetes Deployments</a>

**Comment by slack** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VKQHq9We&#x2F;1-use-kubernetes-deployments"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Use Kubernetes Deployments</a>
