### ISSUE TITLE
Use header based pagination with DRF 3.1+

### ISSUE THREAD

**Issue by helgi** [deis/controller#236]
Django REST Framework 3.1+ adds another pagination way, it now does header based by default

We should investigate if we want to move to a header based pagination format API and if we want to use the versioning (again using headers) API support as well.

This will require updates to the deis client to understand the new format but we will need to think about this from the perspective of operation teams wanting to automate things against Deis AND people that want to write UIs on top of Deis using only the API, so getting input from those types of personas would be helpful

* https://github.com/tomchristie/django-rest-framework/blob/master/docs/topics/3.1-announcement.md
* https://github.com/tomchristie/django-rest-framework/blob/master/docs/api-guide/pagination.md

#101 discovered it but since the code has been reverted

**Comment by Joshua-Anderson** [comment]
@helgi Is this still relevant? I don't think there's any backwards compatible way to make the change now that workflow is GA.

**Comment by helgi** [comment]
It is - 3.0 makes it possible

**Comment by Joshua-Anderson** [comment]
We've never really discussed this, is it possible to release a new major version of the API without releasing a new major version of the deis platform?

**Comment by helgi** [comment]
We haven't talked about it, it would probably be a major rev all over probably

**Comment by bacongobbler** [comment]
closing this as we aren't planning on doing any major API changes within the v2 timeline. Perhaps for v3, but at that time we can re-open this.
