### ISSUE TITLE
Add hooks in build step

### ISSUE THREAD

**Issue by krancour** [deis/controller#239]
Transplanting deis/deis#4822 for consideration here.

@alexw23 writes:

> I'm trying to inject authentication into [composer](https://getcomposer.org) and as such you cannot inject environment variables into a docker build. Would it be possible to check for the existence of a `.prebuild.sh` [here](https://github.com/deis/deis/blob/25653e39a1ac8d76eee28563e2601c9750c3e8a7/builder/rootfs/etc/confd/templates/builder#L128) and `.postbuild.sh` [here](https://github.com/deis/deis/blob/25653e39a1ac8d76eee28563e2601c9750c3e8a7/builder/rootfs/etc/confd/templates/builder#L135) and run those if they exist?

See the original issue for further details, but keep conversation here.

**Comment by Joshua-Anderson** [comment]
How would this compare to using [buildpack-mutli](https://github.com/heroku/heroku-buildpack-multi) and having a pre-buildpack and a post-buildpack?

**Comment by alexw23** [comment]
They wouldn't apply to a docker build

**Comment by Joshua-Anderson** [comment]
@alexw23 How would these differ from a `RUN` in the dockerfile? Would deis inject a `RUN` command into the dockerfile to run these scripts?

**Comment by Joshua-Anderson** [comment]
Deis now has

```
bin/pre-compile
bin/post-compile
```

hooks for buildpacks and dockerbuilder could probably implement them similarly.

**Comment by bacongobbler** [comment]
pre/post-compile hooks were only meant to be a buildpack-related feature to mimic Heroku. A Dockerfile can mimic the same behaviour with RUN commands since the entire build workflow is under the control of the user (whereas the build workflow is under the control of the buildpack). @alexw23 do you have a use case for build hooks in dockerbuilder that cannot be solved with RUN commands?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
