### ISSUE TITLE
Silence /healthz requests in log

### ISSUE THREAD

**Issue by mboersma** [deis/controller#252]
Django logs all HTTP transactions by default, but ideally GET requests on /health-check would be silenced or retargeted for DEBUG level only. Otherwise that constant traffic will crowd out useful log info.

**Comment by helgi** [comment]
This is a log message from `gunicorn` itself and I haven't found a way to silence it by hooking into the filtering system.

We'd be best served by putting nginx in front of gunicorn and using *that* access log which allows you to silence logging per specific routes but even then I don't know if you can have it silence only 200 but let the errors through. Would be our best option overall, beyond living with the the messages.

Or ... we could funnel this into a different syslog output and not stdout

**Comment by bacongobbler** [comment]
alternatively, we can change `httpGet` to an `exec/command` livenessProbe that calls `manage.py healthchecks`

**Comment by mboersma** [comment]
It's true--this is logged by WSGI itself with the equivalent of a `print()` statement, so to silence it we would need to write custom middleware for that level. Messing with `logging` is fruitless for this case. There are a couple examples of such hackery on the net. We could key off the `DEBUG` env var to decide whether or not to log.

**Comment by helgi** [comment]
I was dropping all the way down to doing a extended `gunicorn.glogging` to see if that panned out. Even middleware won't be enough I think to exclude it but I may be wrong
