### ISSUE TITLE
Add support for private Docker registry (such as Quay.io)

### ISSUE THREAD

**Issue by laurrentt** [deis/controller#253]
I currently have a working version (on v1). But it feels hackish and I want to start a discussion on how it could be implemented in v2. In my version of this feature I completely replace the deis-registry by *Quay.io* so I can pull AND push.

So here's what I did (in v1):
* I've edited the `docker run` command inside `deis-controller.service` to mount a local `.dockercfg` inside the container. The `.dockercfg` containing a *quay.io* token is created through a *cloud-init* script (using *Cloudformation*). 
* The original registry didn't need namespacing, but it's obviously impossible to push to quay.io without one, so I've added it as a setting to the controller. (Turns out it it's really easy)
* I've made the `insecure_registry` parameter configurable.

What it missed:
* When using a service such as *Quay.io* you no longer need to specify a port since it uses the standard https one. But in Deis, everytime a docker repository is used the port is explicitly specified. That forces you to have 2 sets of credentials: one for `quay.io: ...` and one for `quay.io:443: ...`.
* *Docker-py* can timeout sometime when you creating a new app. I don't know why but the fact that it's waiting for the registry to create the new repo can cause *Docker-py* client to fail. I've worked around this by always creating the docker repository before pushing the image into it.

The goal here is to start a discussion about how we could implement such feature in v2, but I can also provide the code that I did on v1 if anyone is interested.

**Comment by bacongobbler** [comment]
hmm... so the idea here is to completely cut out Deis' registry and just use an auth-backed registry for hosting the cluster's images? To address some of your comments on how this could be accomplished in v2:

> I've edited the docker run command inside deis-controller.service to mount a local .dockercfg inside the container. The .dockercfg containing a quay.io token is created through a cloud-init script (using Cloudformation).

Since v2 now uses the host's docker daemon, The idea is that you would dump the .dockercfg onto each kubernetes minion. For most deployments with kubernetes, they use StaltStack as their configuration management tool, so you'd have to plug into that somehow to get your docker config file on each minion host. See http://kubernetes.io/v1.0/docs/admin/salt.html for more information.

> The original registry didn't need namespacing, but it's obviously impossible to push to quay.io without one, so I've added it as a setting to the controller. (Turns out it it's really easy)

Yeah the assumption is that the images will get dumped into the generic namespace. We used to do a user-based namespacing in the registry, but that got all sorts of ugly once `deis perms` was added into the picture. Perhaps we can make REGISTRY_URL configurable and stop using REGISTRY_HOST:REGISTRY_PORT?

> I've made the insecure_registry parameter configurable.

That is also handled through the configuration management system you use to deploy your kubernetes cluster, whether that's Chef, Puppet, SaltStack, CoreOS' cloud-config, etc.

> When using a service such as Quay.io you no longer need to specify a port since it uses the standard https one. But in Deis, everytime a docker repository is used the port is explicitly specified. That forces you to have 2 sets of credentials: one for quay.io: ... and one for quay.io:443: ...

Same thing: perhaps we can use REGISTRY_URL here instead of host/port.

> Docker-py can timeout sometime when you creating a new app. I don't know why but the fact that it's waiting for the registry to create the new repo can cause Docker-py client to fail. I've worked around this by always creating the docker repository before pushing the image into it.

Perhaps that sounds like a quay issue? The standalone registry has no problem creating new repositories on the fly, so I'm not sure how this would cause it to fail.

Hope this helps! :)

**Comment by laurrentt** [comment]
@bacongobbler Thanks for helping ! I'm definitely going to read more about Kubernetes in the near future.

Regarding the `insecure_registry` option, you said:
> That is also handled through the configuration management system you use to deploy your kubernetes cluster, whether that's Chef, Puppet, SaltStack, CoreOS' cloud-config, etc.
Does that mean that Deis no longer rely on Etcd for configurations ?

**Comment by bacongobbler** [comment]
insecure_registry was never handled by etcd, AFAIK, but yes, we no longer rely on etcd for configuration: https://github.com/deis/workflow/pull/245

**Comment by slack** [comment]
@laurrentt Thanks for the input! Private registry access is most certainly on the list. If not for 2.0 definitely early 2.x. :dancers: 

1. With respect to registry auth are you using Quay "Robot Accounts" and then granting that access to each of the images that you need to deploy or are you using user tokens?
2. Do you have any other registry-auth related functionality that you would _like_ to see?

**Comment by slack** [comment]
Refs:
* deis/deis#4756
* deis/deis#2680

**Comment by aledbf** [comment]
@helgi from #454 
To pull from private registries is required to add `imagePullSecrets` in the spec section:
```
    spec:
      imagePullSecrets:
        - name: priv-reg-name
```

(assuming that the required secret already exists)
````
kubectl create secret docker-registry priv-reg-name \
	--docker-server=<url> \
	--docker-username=<username> \
	--docker-password=<pass> \
	--namespace <app namespace name>
```

**Comment by MaxenceAdnot** [comment]
This is really something missing. Do you plan to add this feature soon ?

**Comment by slack** [comment]
Private registry support is currently top of list for 2.1!

**Comment by rimusz** [comment]
@slack I tried on GKE node to save docker auth to `/.dockercfg and /root/.docker/config.json` but `deis pull ...' from gcr.io still did not work

**Comment by rimusz** [comment]
@slack we should put it as a priority for v2.0 GA, as there is no way to use private registry otherwise

**Comment by mboersma** [comment]
@helgi is this closed by #649 or is there more still to do?

**Comment by helgi** [comment]
I wasn't going to close this until the docs had been written

**Comment by helgi** [comment]
The initial support for Private Registry has landed in Deis Workflow, including docs: https://github.com/deis/workflow/pull/201

Initially we support self-hosted registries with auth and private repos on DockerHub / Quay and somewhat GCR, only via the Long Lived Token (see the docs)

I'll iterate on it soon, with `imagePullSecret`, better ECR / GCR support and all that good stuff.
