### ISSUE TITLE
change dockerfile field to boolean

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#278]
https://github.com/deis/workflow/blob/master/rootfs/api/models.py#L686

This field when blank is considered false, and true when non-blank. We should just change it to a boolean now that we're breaking APIs.

See https://github.com/deis/builder/blob/master/rootfs/etc/confd/templates/builder#L70-L73 and https://github.com/deis/builder/blob/master/rootfs/etc/confd/templates/builder#L189

**Comment by jchauncey** [comment]
moving to rc1
