### ISSUE TITLE
[question]: is there a reason why the rc uses env and not secrets?

### ISSUE THREAD

**Issue by aledbf** [deis/controller#299]
Something like one secret per version or the one secret per app that is updated in each version.

**Comment by bacongobbler** [comment]
it's a holdover from deis v1. Are you referring to something like https://github.com/deis/deis/issues/4480?

**Comment by helgi** [comment]
Not all env vars need to be secrets, at least in my opinion. Particularly because `secrets` are files (until maybe 1.2 or later based on https://github.com/kubernetes/kubernetes/issues/4710) oppose to ENV vars.

If you look at #13 I had brought up the idea of being able to pass in something like `--secret` on `config:set` to achieve what you might want. Is that along the lines of what you want?

**Comment by aledbf** [comment]
>  Are you referring to something like deis/deis#4480?

@bacongobbler yes

**Comment by aledbf** [comment]
>  like --secret on config:set to achieve what you might want

@helgi yes, something like that to protect "important" things :)

**Comment by aledbf** [comment]
@helgi with env vars is not possible to use the authorization plugins (abac)
For instance one user can do a rolling update changing one or more values in env without problem, that is not possible if the user is not allowed to do that.

**Comment by helgi** [comment]
@aledbf I think we are on the same page mostly. Use `k8s` `env` for "less important" and `secrets` (via flag) for "important" things and that gets via the usual `k8s` path ways, probably would expose it as an internal ENV var when that issue lands.

Are you talking about when the user decides to bypass Deis for the rolling update and go directly to k8s? Do you have a link to the auth plugin?

**Comment by aledbf** [comment]
@helgi here
[authorization.md](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/authorization.md)
[example](https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/abac/example_policy_file.jsonl)

**Comment by helgi** [comment]
I'll have to look at it in more detail but there is no way this would cover the `env` portion in the future? Especially when the pod templates become their own real separate resource out from `RCs`?
