### ISSUE TITLE
Destroying a Deis cluster with a live app seems to cause deployments to the same app name to fail on a new cluster

### ISSUE THREAD

**Issue by arschles** [deis/controller#316]
Repro steps:

1. `helm install deis-dev`
2. `git clone example-go`
3. `cd example-go`
4. `deis register deis.$INGRESS_IP.xip.io`
5. `deis keys:add ~/.ssh/id_rsa.pub`
6. `deis create gotest`
7. `git push deis master`
8. `git commit -m “empty” —allow-empty && git push deis master`
9. Verify your app is up: `curl gotest.$INGRESS_IP.xip.io`
10. `helm uninstall deis-dev`
11. Notice the gotest namespace is still there
12. `helm install deis-dev`
13. `git remote remove deis`
14. Repeat steps 4-7
15. Verify that the app is still on the old v2 version: `curl gotest.$INGRESS_IP.xip.io`

Also, if you kubectl get pod —namespace=gotest, you’ll see the old v2 pod is still running

**Comment by krancour** [comment]
I think this is to be expected.  The only circumstance under which I'd expect this _not_ to be a problem would be if cluster state (i.e. database, registry, etc. and their underlying object storage) were surviving uninstall/re-install, in which case, you'd be picking up from where your old cluster left off.  I think this problem will be solved implicitly by solving the persistent storage problem.

**Comment by slack** [comment]
In the case of apps managed both by deis and "native" applications directly running in k8s, we should do the right thing. If we can't create the namespace because it already exists, I would expect a 409 conflict: application name not available. Make sense?

**Comment by jchauncey** [comment]
@slack i agree that sounds like a good way to help with this problem

**Comment by arschles** [comment]
+1 to the 409 :+1:

**Comment by helgi** [comment]
If a user is creating an application for the first time that is pretty easy to pull off, but what should we do if we are recovering a database to an existing cluster *or* people are using the recovery process to merge clusters?

That'd be undefined behaviour and somewhat out of scope of this ticket but it is a potential behaviour that may be very hard to protect against
