### ISSUE TITLE
Provide server version info in `deis version`

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#329]
From @jchauncey's comment in https://github.com/deis/deis/issues/4674:

> It would be nice if the deis cli had a version command that returned the version of the server running and the version of the cli (like the docker version command)

We could add a flag to `deis version` (#328) to provide more verbose information similar to `docker version`, like so:

```
><> deis version -a
Client version: 2.0.0-dev
Client API version: 2.0
Go version (client): go1.5.2
Git commit (client): foobar
OS/Arch (client): linux/amd64
Server version: 2.0.0-dev
Server API version: 2.0
Go version (server): go1.5.2
Git commit (server): foobar
OS/Arch (server): linux/amd64
```

Alternatively, We could turn it into a JSON object for formatting:

```
><> deis version -a
{
  "Client" {
    "Version": "2.0.0-dev",
    "APIVersion": "2.0",
    "GoVersion": "go1.5.2".
    "Commit": "foobar",
    "Arch": "amd64",
    "OS": "linux"
  },
  "Server": {
    "Version": "2.0.0-dev",
    "APIVersion": "2.0",
    "GoVersion": "go1.5.2".
    "Commit": "foobar",
    "Arch": "amd64",
    "OS": "linux"
  }
```

Which could be handy in the future for features like `deis version -f '{{.Client.Version}}'`, which formats the version output through the given Go template (similar to `docker inspect -f`):

```
><> deis version -a -f '{{ .Client.Version }}'
2.0.0-dev
```

**Comment by helgi** [comment]
Are docs the only thing left?

**Comment by bacongobbler** [comment]
no, we still need to implement this.

**Comment by arschles** [comment]
Note that https://github.com/deis/workflow-cli/issues/25 tracks client side work, and this issue tracks server side work only. I've removed the `client` label accordingly.

**Comment by bacongobbler** [comment]
fixed in https://github.com/deis/workflow-cli/pull/217.
