### ISSUE TITLE
Bold proposal. Rewrite controller in go

### ISSUE THREAD

**Issue by nathansamson** [deis/controller#35]
This could be accomplished by doing it similarly as the client.
Rewrite piece by piece, and if specific feature is not implemented yet let the new implementatio proxy the call to the legacy controller.

Ideally both will run side by side (I know this is frowned upon a bit) in same container, but the legacy one would listen on localhost only. ( I assume this means its not reachable from any other place).

**Comment by Joshua-Anderson** [comment]
Interesting idea!

If I'm understanding properly, the go controller would start out just proxying to the python controller. Then as functionality was ported over the go controller would handle a subset of the requests and still proxy the ones it doesn't understand?

**Comment by arschles** [comment]
:+1: - also we wouldn't necessarily need to run both processes in the same container, just the same pod, and could route to the Go version via the already existing k8s service

**Comment by rimusz** [comment]
@arschles :+1:  :+1:

**Comment by bacongobbler** [comment]
I believe one of the thoughts moving forward is to completely get rid of the concept of a controller and just create kubernetes [ThirdPartyResources](https://github.com/kubernetes/kubernetes/blob/master/docs/design/extending-api.md) by extending the kubernetes API. That may not be for a while though.

Note that I have attempted a total rewrite [some point ago](https://github.com/fishworks/api) but then was stumped on how we would support features like LDAP auth and retaining db support for v1 (the database schema's a bit of a mess when you use an ORM) so I abandoned the project for now.

**Comment by krancour** [comment]
fwiw, I'm also of the persuasion that we should be endeavoring to remove the need to have a controller at all.

**Comment by arschles** [comment]
first I heard of the Third Party Resources proposal, and I'm very much :+1: on that

**Comment by krancour** [comment]
The only problem with it is that third party resources are not enabled by default.  That could be problematic, but even without them, some large chunk of what the controller does today can be replaced by a client that talks directly to the kube API.

**Comment by nathansamson** [comment]
Not knowing how the details (or even global picture in all honesty) of kubernets work
lHow would authentication work in this case? I don't feel very secure that any random user of my deis cluster can talk to the kube API?

**Comment by nathansamson** [comment]
@bacongobbler As far as I see we don't need to keep support for the old DB schema as this will defintily bump deis to V2

**Comment by krancour** [comment]
> How would authentication work in this case? I don't feel very secure that any random user of my deis cluster can talk to the kube API?

Kubernetes does have its own authentication and authorization mechanisms.  They do need to mature more before anything as radical as ditching our controller could happen-- that notion is something that's out on the horizon.

**Comment by jchauncey** [comment]
So like with any effort in rewriting something as integral as the controller, I think we should have a list of what the controller actually does and the use case for that item as it relates to v2. 

With that list you can decide on things like do we need to keep the old database around? What about authentication/authorization? What do the cli's talk to? etc..

**Comment by mboersma** [comment]
> we don't need to keep support for the old DB schema

Why not? Do you imagine a constraint that would prevent us from using the same schema? Breaking things for the sake of breaking them isn't a good plan.

Honestly, this is a proposal that's been tossed out and shot down multiple times. It probably should and will happen someday, but it is not on the roadmap for Deis v2. Let's get that shipped without distractions.

**Comment by gabrtv** [comment]
> So like with any effort in rewriting something as integral as the controller, I think we should have a list of what the controller actually does and the use case for that item as it relates to v2.

Best way to do that is by analyzing the controller REST API surface resource-by-resource.  The use cases don't change, but the implementations will change wildly as we become more Kubernetes-native.

Having thought about this a lot already, my current thinking is as follows: once we transition to a reusable authn service (maybe [dex](https://github.com/coreos/dex)?), we can start shifting API surface from the controller to raw kubernetes APIs.  Authorization can be achievied using [Kubernetes Authz Plugins](http://kubernetes.io/v1.1/docs/admin/authorization.html).

As an example, let's take `deis config:set` endpoints.

A pull request would implement a client-side `deis config:set` that talks to Kubernetes APIs directly, while at the same time removing that API surface from the Python controller.  We lean on end-to-end tests to ensure everything is kosher.  Then wash, rinse, repeat until there's no Python controller left.

I don't want to invest time in rewriting controller APIs that should (in my opinion) be deprecated altogether.

> ..it is not on the roadmap for Deis v2. Let's get that shipped without distractions.

:100:  We are shipping the Python controller for v2. Only caveat is that the REST API surface will _not_ be covered under our SemVer contract.  Only the CLI will.

**Comment by jchauncey** [comment]
> I don't want to invest time in rewriting controller APIs that should (in my opinion) be deprecated altogether.

I think that's what I was getting at with my list. Most of the time I have found that once you have all the things that something does out in the open and you compare it against what you actually need, you end up cutting things out because you find other ways to do it with existing apis.

**Comment by helgi** [comment]
This is not on the agenda anytime soon. We'll come back to this at some point
