### ISSUE TITLE
Remove confd

### ISSUE THREAD

**Issue by helgi** [deis/controller#358]
Right now confd is used for a handful of things, mostly to write out a production configuration that is not done during a test run.

We need to figure out how to source the very few values that are left in confd and how we are going to load different configurations for production vs testing

**Comment by carmstrong** [comment]
:+1:

**Comment by helgi** [comment]
Right now I'm thinking about moving this to pure ENV vars.

@krancour you had opinions on this. Ditching the ability to restart gunicorn on the fly is okay with you

**Comment by krancour** [comment]
@helgi already lgtm'ed the PR for this.  But, yes... I think not being able to restart gunicorn on the fly is ok... unless you have some specific edge case in mind where that's really necessary.
