### ISSUE TITLE
v2.0 API documentation needs updating

### ISSUE THREAD

**Issue by mboersma** [deis/controller#363]
The [MkDocs](http://www.mkdocs.org/) documentation in the `docs/` directory has a placeholder document `docs/src/reference-guide/controller-api/v2.0` for the new API docs. But it doesn't have an `.md` extension and isn't yet included in the docset. The API needs to be documented clearly for beta. This is a manually updated doc, which is annoying, but let's not wait for incorporating Swagger to get this done.

**Comment by helgi** [comment]
http://www.django-rest-framework.org/topics/documenting-your-api/ many automation options. We know swagger doesn't work out of the box

**Comment by bacongobbler** [comment]
let's punt this to v2-stable since we're gonna have to re-write half of our existing documentation anyways
