### ISSUE TITLE
invalid JSON saved to App model

### ISSUE THREAD

**Issue by mboersma** [deis/controller#441]
It appears that an operation like `deis pull -p '{"web":1, "cron"1}'` proceeds without validating the JSON provided on the command line. This can cause a `JSONDecodeError` later that stops workflow from starting up properly--see #438.

**Comment by helgi** [comment]
@aledbf do you know how you inserted that record? The YAML parser in the current CLI should catch things but I'm curious... I'm not able to reproduce things right now

**Comment by helgi** [comment]
I'm going to close this on the count that this was affecting `structures` in the App model which is something only Django writes to. It is not the Procfile handling
