### ISSUE TITLE
certs: determine if domain is valid in certs:attach <cert> <domain>

### ISSUE THREAD

**Issue by vdice** [deis/controller#475]
Currently, although `certs:attach <cert> <domain>` will properly error out if `<cert>` is bogus/non-existent, it doesn't if `<domain>` is similarly non-existent.  Consider the following unit test, which is currently failing (err is nil):

```
if err := Attach(&client, "test-example-com", "non-existent.domain.com"); err == nil {
   t.Fatal("An Error should have resulted from the attempt to attach a valid cert to a non-existent domain")
 }
```

^^ exists in comments, can enable with this fix

**Comment by helgi** [comment]
Very odd given https://github.com/deis/workflow/blob/master/rootfs/api/models/certificate.py#L165 - Will investigate

**Comment by arschles** [comment]
Note that deis/workflow-cli#25 was created to track client side work. This issue should only track server side work, if any is necessary. The `client` label has been removed accordingly

**Comment by helgi** [comment]
```
deis certs:attach new-cert foo.com
Attaching certificate new-cert to domain foo.com... Error:
404 Not Found
detail: Not found.

controller  (ticket_706>) $ deis domains:add foo.com -a zanier-zirconia
Adding foo.com to zanier-zirconia... done

Attaching certificate new-cert to domain foo.com... done
```

While maybe not descriptive the API is doing the right thing
