### ISSUE TITLE
Port error after #473

### ISSUE THREAD

**Issue by aledbf** [deis/controller#485]
Before #473 [this](https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L236) was `$port`. New apps set 8080 when the value for `PORT` is 5000

**Comment by helgi** [comment]
@aledbf did you run into a bug? Can you give me steps to reproduce. 

The fact it is hardcoded as `8080` there shouldn't matter since we pull the port from the docker image later on in the flow. see https://github.com/deis/workflow/blob/master/rootfs/scheduler/__init__.py#L334-L341

**Comment by helgi** [comment]
Haven't heard anything more about this. Things seem to work as intended despite what is set as default

@aledbf Please reopen if you think it is still a problem
