### ISSUE TITLE
Swap "minio" for generic "object storage"

### ISSUE THREAD

**Issue by krancour** [deis/controller#521]
See here: https://github.com/deis/controller/blob/745f7e1504ae6cb9374a94d77f37eabe48578788/rootfs/scheduler/__init__.py#L46-L66

It would probably be more proper to not use "minio" here and, instead, not assume or hint at the use of any particular object storage provider by using a more generic term like "object storage" instead.

A large benefit to this is cleaner charts.

cc @arschles @helgi

**Comment by arschles** [comment]
This seems related to the following two issues, either of which may change the scope of this one or render it obsolete:

- https://github.com/deis/slugrunner/issues/18 will mean that we'll be using the new `deis-objectstorage` secret, which is a more generic way to specify the object storage endpoint info and credentials
- https://github.com/deis/controller/issues/182 will mean that we won't need to pass slugrunner pods an object storage secret at all. Instead, the controller would be able to pass the slugrunner a pre-signed URL to the object, and the slugrunner will be able to download the slug without any other credentials.

**Comment by helgi** [comment]
Doesn't this duplicate #458
