### ISSUE TITLE
structure object is empty on initial provision

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#526]
After a `git push deis master`, the app structure object is empty, even though a process has been deployed:

```
><> curl -s deis.10.245.1.3.xip.io/v2/apps/go -H "Authorization: token 8d1597d250b21aa4ccddfedc74a25fed9287a4a0" | jpretty
{
    "created": "2016-03-17T18:58:32UTC",
    "id": "go",
    "owner": "bacongobbler",
    "structure": {
    },
    "updated": "2016-03-17T19:06:28UTC",
    "uuid": "cd059042-1d6f-4f08-8d9d-f770c651aec3"
}
```

However, after I scale the process up to 3 instances, I get this:

```
><> curl -s deis.10.245.1.3.xip.io/v2/apps/go -H "Authorization: token 8d1597d250b21aa4ccddfedc74a25fed9287a4a0" | jpretty
{
    "created": "2016-03-17T18:58:32UTC",
    "id": "go",
    "owner": "bacongobbler",
    "structure": {
        "web": 3
    },
    "updated": "2016-03-17T19:08:43UTC",
    "uuid": "cd059042-1d6f-4f08-8d9d-f770c651aec3"
}
```

We should probably add an endpoint to get the replication controller and remove the `structure` field since `GET /v1/apps/go/pods` shows all active pods, but not the desired number of pods (which is the intent of `structure`).

**Comment by helgi** [comment]
#497 should fix that, if you have time can you verify?

**Comment by helgi** [comment]
We're keeping `structure` for now. Otherwise we can not rehydrate `k8s` if we are creating a whole new deis setup based on a database backup if we only rely on the `RC` replicas count

**Comment by bacongobbler** [comment]
okay if that's the case, we should probably update the structure when we provision the first pod so we can re-hydrate k8s.

**Comment by bacongobbler** [comment]
I'll go ahead and test #497 and see if that fixes things, but we should also add a unit test in there for this specific issue so we can close this.

**Comment by bacongobbler** [comment]
No, #497 does not fix this for me.

```
><> curl -s deis.10.245.1.3.xip.io/v2/apps/go -H 'Authorization: token 632ca4af43150dac25886c8002f15cecaf2474bb' | jpretty
{
    "created": "2016-03-17T20:56:13UTC",
    "id": "go",
    "owner": "bacongobbler",
    "structure": {},
    "updated": "2016-03-17T20:56:13UTC",
    "uuid": "4ad54a7f-1b1d-4390-a50f-986a11db8bf9"
}
```

**Comment by helgi** [comment]
I find the odd given https://github.com/deis/controller/pull/497/files#diff-46b526ca4557d831be62e15b255e5f47R319 is a special case around if `structure` is empty, populating it and then saving.

Have you inspected the DB? It could just be like that in the return format from the serializer but that would be weird as well

**Comment by bacongobbler** [comment]
```
><> kd exec -it deis-database-6zdx8 gosu postgres psql 7bCwNaU7HEDJVryYJqjxkNOK3FKfuhnR
psql (9.4.6)
Type "help" for help.

7bCwNaU7HEDJVryYJqjxkNOK3FKfuhnR=# SELECT * from api_app;
                 uuid                 |            created            |           updated            | id | structure | owner_id 
--------------------------------------+-------------------------------+------------------------------+----+-----------+----------
 4ad54a7f-1b1d-4390-a50f-986a11db8bf9 | 2016-03-17 20:56:13.861386+00 | 2016-03-17 20:56:13.86224+00 | go | {}        |        1
```

**Comment by bacongobbler** [comment]
Never mind. I was using an older image. Let's close this once #497 is merged

**Comment by helgi** [comment]
#497 is merged
