### ISSUE TITLE
GET /v2/apps/go/pods output timedate is inconsistent

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#625]
the pods output returns a Z timestamp:

```
><> curl -s http://deis.10.245.1.3.xip.io/v2/apps/go/pods -H 'Authorization: token 61dec82c88cc373353c5cf7dda1888cd163e18dd' | jpretty
{
    "count": 1,
    "results": [
        {
            "name": "go-v2-cmd-e7dej",
            "release": "v2",
            "started": "2016-04-11T20:52:37Z",
            "state": "up",
            "type": "cmd"
        }
    ]
}
```

Whereas the rest of the API uses `UTC` as the timezone (which is [wrong according to ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#UTC), but consistent):

```
><> curl -s http://deis.10.245.1.3.xip.io/v2/apps/go -H 'Authorization: token 61dec82c88cc373353c5cf7dda1888cd163e18dd' | jpretty
{
    "created": "2016-04-11T20:52:19UTC",
    "id": "go",
    "owner": "bacongobbler",
    "structure": {
        "cmd": 1
    },
    "updated": "2016-04-11T20:52:37UTC",
    "uuid": "1c2b1fdd-7f18-4ba1-b291-d9dc8d809229"
}
```

**Comment by helgi** [comment]
@bacongobbler I'm not sure I would call it a bug, it is mostly that we are passing through the datetime format that comes from the k8s API. Z and UTC are the same thing but I could also try to reformat it just to keep things in sync

At the time it didn't seem worth it since the CLI knew how to deal with both formats

**Comment by bacongobbler** [comment]
In terms of ISO 8601, UTC should not be used at all and Z should be used. I was just posting this so we're aware of this change.

**Comment by helgi** [comment]
Actually, here is why `DEIS_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S%Z'` - The UTC is from the DB (postgres or the ORM), we use Z everywhere else, including the pod output

Bigger question then is, should we try to coheres Django to output Z or should we fix this due to inconsistency

**Comment by helgi** [comment]
DRF has ISO 8601 as all the defaults, hmmm http://www.django-rest-framework.org/api-guide/settings/#date-and-time-formatting

**Comment by bacongobbler** [comment]
It's probably better to fix up the API's date time format, but we couldn't before because that would break our semver contract. It's likely https://github.com/deis/controller/blob/master/rootfs/deis/settings.py#L148

**Comment by helgi** [comment]
We set the above `DEIS_DATETIME_FORMAT` which is ISO 8601 and by default DRF sets ISO 8601 anyway, so I'm not convinced (yet) that changing the value is the fix

**Comment by bacongobbler** [comment]
Changing DEIS_DATETIME_FORMAT seems to get us halfway there:

```
><> curl -s http://deis.10.245.1.3.xip.io/v2/apps -H 'Authorization: token 61dec82c88cc373353c5cf7dda1888cd163e18dd' | jpretty
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "created": "2016-04-11T20:52:19.762454Z",
            "id": "go",
            "owner": "bacongobbler",
            "structure": {
                "cmd": 1
            },
            "updated": "2016-04-11T21:34:04.667978Z",
            "uuid": "1c2b1fdd-7f18-4ba1-b291-d9dc8d809229"
        }
    ]
}
```

But now we're stuck with an unnecessarily precise time stamp.

**Comment by helgi** [comment]
interesting, what confuses me is we already define Z ourselves so they are doing an internal translation?

**Comment by helgi** [comment]
Well apparently the precision is part of a sub-standard that they are following, what a pain :|
