### ISSUE TITLE
controller doesn't send application event logs to the logger

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#638]
In v1, any call to `log_event` in models.py would write to the application's logs, which was a hack to get logspout to pick up the log and write it to the application's log file: 

https://github.com/deis/deis/blob/master/controller/api/models.py#L59-L62
https://github.com/deis/deis/blob/master/controller/api/models.py#L1077-L1078
https://github.com/deis/deis/blob/master/controller/api/models.py#L224-L229

In v2, event logs like `bacongobbler created initial release` are no longer available via `deis logs` because the controller doesn't have a way to make fluentd pick these up for the application.

**Comment by jchauncey** [comment]
Use this env var to connect to the syslog port for logger - `DEIS_LOGGER_SERVICE_PORT_TRANSPORT`

**Comment by jchauncey** [comment]
Granting and Revoking access - https://github.com/deis/deis/blob/5999c6c1a42fbdecab7a656c636f5bc4b67a7be3/controller/api/views.py#L467

```
        models.log_event(app, "User {} was granted access to {}".format(user, app))
        models.log_event(app, "User {} was revoked access to {}".format(user, app))
```

**Comment by jchauncey** [comment]
we are going to fix this in logger not controller
