### ISSUE TITLE
restore process type branch logic

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#647]
This is so we can retain backwards compatibility for changes like #646.

Old v1 tests as shown [here](https://github.com/deis/deis/blob/fc65359c2ba5541aadf35836940bf312007956de/controller/api/tests/test_container.py#L450-L499)

**Comment by helgi** [comment]
https://github.com/deis/controller/blob/master/rootfs/api/tests/test_pods.py#L479-L535 that test still exists, the updated version may not be exercising it correctly? what are we missing?

**Comment by helgi** [comment]
@bacongobbler Can you look at my reply from a while back? Still wondering what went missing, if anything?

**Comment by bacongobbler** [comment]
nothing, all good.
