### ISSUE TITLE
Should we create a service if the app doesn't expose any port

### ISSUE THREAD

**Issue by kmala** [deis/controller#656]
Currently when we deploy a docker app we expose 5000 port as default if nothing is exposed by the image.Should we continue to be doing it or move to a different approach where we create a empty service and add a non routable tag to it so that router handles any incoming requests properly.

**Comment by helgi** [comment]
You can't create a Service without a port

**Comment by krancour** [comment]
Should we maybe just not create the service at all in that case.

**Comment by kmala** [comment]
currently we create a service during a `deis create` operation during which we don't have any information about the type of process it is going to be...if we have to go with not creating a service we need to move that operation to build time than create time.

**Comment by helgi** [comment]
And doing that means you couldn't apply Domains, Configs and other things to an app until after it has been deployed. Or we have to get much smarter in those models, as some of them depend on the SVC being around

**Comment by bacongobbler** [comment]
closing as the question has been answered and there is nothing actionable in this ticket.
