### ISSUE TITLE
remove unnecessary application events

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#674]
Anything kubernetes or scheduler-related that aren't human readable messages or important to the application operator should be removed. For example:

```
><> deis logs
INFO [go]: bacongobbler created initial release
INFO [go]: domain go added
INFO [go]: bacongobbler deployed 779ca3d
INFO [go]: Cleaning up RCS for releases older than v2 (latest)
INFO [go]: Cleaning up orphaned environment var secrets
go-v2-web-n1ykl -- 2016/04/27 18:20:36 Successfully copied home/go:git-779ca3d7/push/slug.tgz to slug.tgz
go-v2-web-n1ykl -- 2016/04/27 18:20:36 listening on 5000...
go-v2-web-n1ykl -- 2016/04/27 18:23:03 10.246.44.1 GET /
go-v2-web-n1ykl -- 2016/04/27 18:23:03 10.246.44.1 GET /favicon.ico
```

These lines should either be removed or made more generic because it is too verbose for application logs. The user should not know about the platform infrastructure. This is still important information for the platform administrator, however.

The log lines I'm talking about are specifically

```
INFO [go]: Cleaning up RCS for releases older than v2 (latest)
INFO [go]: Cleaning up orphaned environment var secrets
go-v2-web-n1ykl -- 2016/04/27 18:20:36 Successfully copied home/go:git-779ca3d7/push/slug.tgz to slug.tgz
```

That last message is a symptom of https://github.com/deis/builder/issues/306 and https://github.com/deis/object-storage-cli/issues/10

**Comment by helgi** [comment]
Right now they are `INFO`, we could make them `DEBUG` instead, so it is around if people want the verbosity, how does that sound?

**Comment by bacongobbler** [comment]
I don't think `deis logs` or the logger filters by log level. It dumps anything in the application logs.

**Comment by helgi** [comment]
We'd make it do that if it doesn't already. I don't think we should show any DEBUG messages anyway unless DEBUG is on
