### ISSUE TITLE
Retry loops could be simplified by retrying lib

### ISSUE THREAD

**Issue by mboersma** [deis/controller#708]
The [`retrying`](https://pypi.python.org/pypi/retrying) python library could simplify several loops in controller code by replacing them with a `@retry` decorator.

See #689 and #703.

**Comment by kmala** [comment]
i had added it as part of my PR https://github.com/deis/controller/pull/689

**Comment by helgi** [comment]
I would add https://pypi.python.org/pypi/retry/ and https://pypi.python.org/pypi/backoff into the mix as the `retrying` lib has not had a release since 2014

**Comment by helgi** [comment]
We're going to go with the `backoff` library going forward - There are PRs in place (and merged as well in some cases) that make use of it
