### ISSUE TITLE
Default ports for images and auto-discovery from images

### ISSUE THREAD

**Issue by helgi** [deis/controller#721]
Currently we default to port `5000` for `buildpacks` and for the rest the port is discovered from the image and defaults to `5000` if nothing is found.

https://github.com/deis/controller/pull/718 breaks that by adding External Registry support using `imagePullSecret` in k8s oppose to pulling it to the Deis internal registry.

The problem with that is `_get_port` pulls the image and inspects it. However it never authenticates. There is a strong assumption that the image is already available in the local docker daemon.

We need to figure out what we want to do, and here are 2 different approaches:

## Auth against registry for `_get_port`

This approach would add in authentication capabilities into `_get_port` like `publis_release` in our `dockerclient`, allowing `_get_port` to pull the image and inspect as normally. No external changes and auto-discovery of port works.

Downside: Having to download the docker image to the controller that is otherwise not required. This operation can be very heavy and expensive if we are dealing with larger images. It bloats up the controller.

Upside: auto-discovery works

## Require people to specify a `$PORT` if they use something different than `5000`

When deploying applications that require external registries then we'd default to `port = 5000` (we could also move to a more traditional 8080) and if the user wants to use a different port then they will have to do `deis config:set PORT=3000 -a <app>` to get their deployment working.

Downside: auto-discovery of port doesn't work anymore

Upside: not bloating up the Controller and downloading a image to get a simple port number

**Comment by jchauncey** [comment]
i like the second proposal here

**Comment by arschles** [comment]
:+1: on the second proposal as well

**Comment by mboersma** [comment]
> auto-discovery of port doesn't work anymore

Is that problem specific to the `deis pull` workflow then? Or would this break `git push` for Dockerfiles without `ENV PORT=5000` as well? (I assume this is irrelevant to buildpack `git push`.)

**Comment by helgi** [comment]
It breaks for non-buildpacks since we should be just auto going to `5000` for anything with slugs

**Comment by bacongobbler** [comment]
considering that we want to eventually support applications [with multiple ports exposed](https://github.com/deis/deis/issues/3069), I would side with option 1. option 2 means manual work for the user, which shouldn't be required since we have the information already given to us through inspecting the container image. heavy and expensive, but the UX is significantly improved and gives us more flexibility to introduce features like deis/deis#3069 in the future.

**Comment by mboersma** [comment]
> we could also move to a more traditional 8080

I think the default port should stay 5000 in any case, for compatibility with Heroku and Deis v1.

**Comment by mboersma** [comment]
I prefer option 1) "do the heavy lifting" because it's a better UX overall, and because it's more in keeping with past behavior. Although I agree there will be degenerate cases where the performance suffers.

**Comment by helgi** [comment]
For reference https://devcenter.heroku.com/articles/runtime-principles says Heroku exposed a `$PORT` for you, but also defaults to `5000`, which also can be something else

**Comment by helgi** [comment]
Here is another thing to remember, this is supporting *private* external registries that do not pull into the Deis Registry. This not something we supported in v1, so there is no legacy to keep.

**Comment by kmala** [comment]
adding existing similar issue https://github.com/deis/controller/issues/138

**Comment by krancour** [comment]
I think pulling an image down to the controller _just_ to make a determination about what port it exposes seems pretty heavy-handed.  Especially for large images, that could add a significant amount of time to the deployment.

This issue only, very specifically, affects `deis pull` from _private_ repos.  I think with defensible reasons for _not_ pulling the image to the controller (deploy time _and_ security), asking users to provide a hint about what port is exposed is a small concession that we can easily document and that I think most users needing to use private repos in the first place will be perfectly happy to make.

If we were really concerned about UX, we could add a `--port` flag to `deis builds:create` / `deis pull` and interactively ask the user for the port if they don't voluntarily provide it.

**Comment by helgi** [comment]
@krancour Alternatively we could also support the Heroku workflow as defined in https://devcenter.heroku.com/articles/runtime-principles

> The [port to bind](https://devcenter.heroku.com/articles/dynos#web-dynos) to is assigned by Heroku as the PORT environment variable

We set `$PORT` to `5000` and people can overwrite it via `config:set`.

**Comment by slack** [comment]
I'm partial to providing a platform default of `5000`, exposed via `$PORT` which can be overridden by the customer.

Making the configuration explicit also helps when we move to multi-port configurations. Most likely, if both ports are HTTP, we'll need to gather routing information (domains, url paths) and associate it with the port mapping. I don't think we will be able to get away with inference if we live in a multi-port universe.

Along with the fact that this simplifies controller interactions with docker registries is a big win!

**Comment by gabrtv** [comment]
I spoke with @helgi about this earlier and have been noodling for a bit... 

Having access to the image metadata feels pretty important even if we can find workarounds for things like `$PORT`. Do we really want the controller orchestrating images while being _blind_ to what's in them?  Feels wrong to me.

Before we pick option 1 or 2, I want to make sure we've exhausted efforts to garner image metadata via the Docker Registry API (i.e. without pulling the images down).

**Comment by helgi** [comment]
@gabrtv I have looked before (because having an API to fetch port info seems sensible) and took the time to look again - Right now the Registry API does not offer that beyond inspect an image you have already pulled into your graph.

Based on all the feedback in here and talking to people then I am going to go with option 2
