### ISSUE TITLE
Deis Pull using incorrect ports

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#775]
If an app is previously setup through a git push the port is detected correctly.  If a user switches to using ```deis registry``` and does not set the PORT value it will override the previous ports and use 5000.  The controller will also scale down the old service even though the new port never passes the healthcheck.

#706

**Comment by bacongobbler** [comment]
From what I understand that is the design, though that is not defined in the docs. pinging @helgi on this one

**Comment by sstarcher** [comment]
@bacongobbler so even if a HEALTHCHECK_PORT is defined it defaults it to 5000...

From a user perspective erroring out would be prefered vs using 5000.

**Comment by sstarcher** [comment]
It also does not honor HEALTHCHECK_PORT

**Comment by sstarcher** [comment]
When attempting to do ```deis config:set PORT=80``` the WARNING about 5000 goes away, but the service fails.

```
ERROR [public]: public-v34-cmd (app::deploy): failed to update Service "public" in Namespace "public": 422 status code 422
{'reason': 'Invalid', 'status': 'Failure', 'apiVersion': 'v1', 'code': 422, 'message': 'Service "public" is invalid: spec.ports[0].targetPort: Invalid value: "80": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be adjacent to other hyphens): e.g. "http"', 'details': {'causes': [{'message': 'Invalid value: "80": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be adjacent to other hyphens): e.g. "http"', 'reason': 'FieldValueInvalid', 'field': 'spec.ports[0].targetPort'}], 'name': 'public', 'kind': 'Service'}, 'metadata': {}, 'kind': 'Status'}
```

**Comment by helgi** [comment]
If you are using `deis registry` with an external registry then you will have to specify a `PORT` if `5000` isn't your yam. I will open up a documentation ticket and look at if we can make it error out.  That we are not pulling images locally to discover the port (both slow and insecure)

`HEALTHCHECK_PORT` is not used, I need to remove it from the docs and the config object. For a good 
while now we've instead been health checking on the port that the service is using
