### ISSUE TITLE
Validate that PORT config option is in fact an int

### ISSUE THREAD

**Issue by helgi** [deis/controller#777]
Right now it is possible to do `PORT=dog` and we'll happily pass that along everywhere. While `PORT` is in the very broad `config:set` space then we can still do some special validation and throw a nice error message

See https://github.com/deis/controller/pull/776 for more info

**Comment by bacongobbler** [comment]
probably can do that for any other non-string value passed to k8s as well like the initial delay timeout etc.

**Comment by helgi** [comment]
Yeah, for sure, for health check stuff I was planning on doing it as part of https://github.com/deis/controller/issues/603 - at that point it is more special cased and we can a bit more cleanly do validations
