### ISSUE TITLE
limits cpu shares

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#786]
The documentation for deis limits:set claims it is setting cpu shares.  That is not the case it is requesting whole cpus.

```
    With --cpu, units are represented in the number of cpu shares. For example,
    'deis limit:set --cpu cmd=1024' will restrict all "cmd" processes to a
    maximum of 1024 cpu shares.
```

Reading that I would believe
`deis limit:set --cpu cmd=1024` would set the pod definition to contain

```
    Limits:
      cpu:	1024m
```

The actual definition is
```
    Limits:
      cpu:	1024
```

**Comment by bacongobbler** [comment]
that is correct. From [the kubernetes documentation](http://kubernetes.io/docs/user-guide/compute-resources/):

> # How Pods with Resource Limits are Run

> When kubelet starts a container of a pod, it passes the CPU and memory limits to the container runner (Docker or rkt).
> When using Docker:
> - The spec.container[].resources.limits.cpu is multiplied by 1024, converted to an integer, and used as the value of the --cpu-shares flag to the docker run command.
> - The spec.container[].resources.limits.memory is converted to an integer, and used as the value of the --memory flag to the docker run command.

Are you seeing different behaviour on your nodes?

**Comment by sstarcher** [comment]
@bacongobbler yep, I had a similar problem a little while back between different k8s versions.  The value deis is currently supplying is x1024 to high.

**Comment by sstarcher** [comment]
@bacongobbler This is not a docs issue.  If the expected behavior of is to set 1024 cpu shares for the kubernetes pod that is not the current behavior. ```deis limit:set --cpu cmd=1024 ```

The current actual result at least in Kubernetes 1.2.4 is to set 1024 cpus

**Comment by bacongobbler** [comment]
We are just passing the value through to kubernetes. If they now multiply it by 1024 to denote cpus, then we need to document `deis limits:set --cpu cmd=0.5` will limit your process to half of a cpu.

**Comment by sstarcher** [comment]
The pod definitions for limits accepts units.  Currently Deis is supplying a raw number of X you could also supply Xm to specify mili for the unit.

**Comment by helgi** [comment]
https://github.com/deis/controller/blob/master/rootfs/api/serializers.py#L18 - the validation we allow for is both passing in straight up numbers and milli units - The `[m]` part is optional.

So to me the question becomes, do we always want to convert to milli units and forgo the ability to pass in of raw k8s or do we only want to fix docs in this situation. Or ask people to input milli units via `deis limits`

**Comment by bacongobbler** [comment]
Personally I think it's better to fix the documentation, given that we should allow both types here as kubernetes does. Users of kubernetes will want to supply both a static number of CPUs via a float value or in milli units.

**Comment by gabrtv** [comment]
I don't feel strongly as long as we are consistent.  I will say that for usability reasons, most cluster managers (i.e. Mesos, Swarm, Kubernetes) have moved away from CPU shares -- an arcane concept -- to number of CPUs, which is a lot more understandable.

**Comment by sstarcher** [comment]
Ahh if you already support raw units and `m` I would vote for just fixing the docs.

**Comment by bacongobbler** [comment]
ok, I'll take a crack at that.
