### ISSUE TITLE
cannot set PORT in container

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#800]
maybe I'm testing this wrong but:

 - deployed workflow-v2.0.0 (deis/charts#282)
 - deployed example-go as a buildpack app
 - `deis config:set PORT=80`

I expected the envvar PORT in the container to be 80 and for the container to fail, but instead PORT is still 5000. Is this expected behaviour that we cannot overwrite PORT in the container unless it is explicitly a private repo app?

potentially related to #767

**Comment by helgi** [comment]
You should be able to - did you go on the container and make sure it prints out 80 for $PORT ?

**Comment by bacongobbler** [comment]
yup.

```
><> deis run env
Running 'env'...
HOSTNAME=go-v3-run-nn62y
GO_PORT_80_TCP=tcp://10.247.137.65:80
GO_PORT=tcp://10.247.137.65:80
KUBERNETES_PORT=tcp://10.247.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
GO_PORT_80_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.247.0.1
GO_PORT_80_TCP_PORT=80
WORKFLOW_RELEASE=2.0.0-dev
GO_SERVICE_PORT_HTTP=80
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/bin
DEIS_MINIO_SERVICE_HOST=None
PWD=/app
BUILDER_STORAGE=s3
HOME=/app
SHLVL=1
DEIS_MINIO_SERVICE_PORT=None
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
GO_SERVICE_HOST=10.247.137.65
PORT=5000
KUBERNETES_PORT_443_TCP_ADDR=10.247.0.1
GO_PORT_80_TCP_ADDR=10.247.137.65
KUBERNETES_PORT_443_TCP=tcp://10.247.0.1:443
GO_SERVICE_PORT=80
_=/usr/bin/env
><> deis config
=== go Config
PORT      80
```

**Comment by bacongobbler** [comment]
nvm. buildpacks are hardcoded to use port 5000. deis pull apps can set port 80 as they please.
