### ISSUE TITLE
Output kubernetes error to controller log when app deploy fails

### ISSUE THREAD

**Issue by dmcnaught** [deis/controller#816]
Reproduce:
  Port is not set correctly on docker image app from private registry (quay)
  deis pull ...

Eg output in controller pod log
ERROR [hdf-json-api]: hdf-json-api-v3-cmd (app::deploy): Could not scale hdf-json-api-v3-cmd to 1. Deleting and going back to old release

https://github.com/deis/controller/blob/139e7c1fa4dce245c0db961b8007408b51d6e896/rootfs/scheduler/__init__.py#L414-L419

cc @helgi

**Comment by helgi** [comment]
in https://github.com/deis/controller/pull/975 I made it so that more information is relayed back to the user via the API. Also logged in the controller logs. It will be part of 2.4

Give that a spin and see if you were talking about a different behaviour
