### ISSUE TITLE
Can't login after rebooting the k8s node.

### ISSUE THREAD

**Issue by monaka** [deis/controller#825]
There was no trouble after installation finished.
All are OK, registering my account, adding my keys, and deployment.

But after rebooting k8s node for maintainance, I can't access to my controller.
I tried to login. It shows message like this.

```
$ ./deis login http://deis.****/
username: monaka
password: 
Error: 
400 Bad Request
non_field_errors: Unable to log in with provided credentials.
```

I also tried accessing services directly in the k8s node. But the results are same.

Where should I check for trouble shooting?

**Comment by helgi** [comment]
Is your database / minio backed up to s3 or GCS?

Try running register again, changes are your data was lost if you did not persist backups anywhere

**Comment by bacongobbler** [comment]
Indeed. The best way to check would be to go into your database container using the [kubectl troubleshooting guide](https://deis.com/docs/workflow/troubleshooting/kubectl/) and check the state of your database. I agree with @helgi that the likely case is that you were running minio instead of backing the database up with S3/GCS and lost your data when minio was rebooted.

**Comment by monaka** [comment]
I don't have database /minio backups.
I tried to register my account again and it was succeeded.
But the result of `deis apps` is empty. (Should be 2 apps shown.)

What is the reason the account is lost?
There had a few hours between account registration and reboot.
So the database will be backup to Minio.
In this case data in Minio was lost?

**Comment by bacongobbler** [comment]
@monaka yes. See [the production deployments](https://deis.com/docs/workflow/managing-workflow/production-deployments/#running-workflow-without-minio). If minio is rebooted, all your data is lost.

**Comment by monaka** [comment]
@bacongobbler, I see.
I have misunderstanding the Minio instance in Workflow is parsistent smilar to the store in Deis v1.
I close this issue as it is an expected behavior.

I decided to use Deis v2 for production. So I'll set up my storage soon.
Thanks @heigi @bacongobbler for your support.
