### ISSUE TITLE
No type checking for /v2/auth/tokens/

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/controller#828]
So

`POST  /v2/auth/tokens/` Body: `{"all": "test"}`

Python evaluates `"test"` to `True`, which is probably not what the user expected.

Not a big deal, but it should get fixed up at some point.

**Comment by helgi** [comment]
What would the user expect? Despite using `all` as the key but passing in `test` as the value then they'd expect `test` to be reset?

In the API we only look at the key and we don't care about the value https://github.com/deis/controller/blob/master/rootfs/api/views.py#L133 - only when using `username` it matters

**Comment by helgi** [comment]
I think the current way of things working is fine - If someone comes up with a better way then re-open this ticket

**Comment by Joshua-Anderson** [comment]
Yeah, sorry I overlooked this. This was the result of a typo where I set `all` instead of username. I think there are 2 options:

1. treat `all` as a boolean field
2. treat `all` as set/unset.

I think the current behavior of set/unset is probably fine, it's just has a higher likelihood of confusion than option 1.

**Comment by helgi** [comment]
How does the boolean scenario look from an API perspective

**Comment by Joshua-Anderson** [comment]
Basically only `{ "all": true}` or `{ "all": false}` (default)  would be accepted.

**Comment by helgi** [comment]
Does the SDK and the docs treat it that way already?

**Comment by Joshua-Anderson** [comment]
The SDK treats it that way, and the docs have a typo in them and treat it as a string:

```
{
    "username" : "test"
    "all" : "true"
}
```
