### ISSUE TITLE
Trying to scale a nonexistent process type results in 400, not a 404

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/controller#830]
`POST /v2/apps/<id>/scale/` Body: `{"foo": 2}`

will return 400: `{"detail":"Container type foo does not exist in application"}`

**Comment by bacongobbler** [comment]
I think this is intentional. /v2/apps/appid/scale is a a valid endpoint, but the data received is incorrect.

**Comment by Joshua-Anderson** [comment]
Over most of the rest of the API, we use `get_object_or_404` when loading child objects, so in this situation they return a 404.
