### ISSUE TITLE
liveness probe success threshold

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#873]
When setting success-threshold to anything, but 1 deis errors.

```
 deis healthchecks:set liveness httpGet -p /status --success-threshold=3 -- 8080
```

```
Applying livenessProbe healthcheck... Error: Unknown Error (400): map[detail:app-v47-cmd (app::deploy): ('failed to create ReplicationController "app-v47-cmd" in Namespace "app": 422 status code 422\n{\'status\': \'Failure\', \'metadata\': {}, \'message\': \'ReplicationController "app-v47-cmd" is invalid: spec.template.spec.containers[0].livenessProbe.successThreshold: Invalid value: 3: must be 1\', \'reason\': \'Invalid\', \'code\': 422, \'kind\': \'Status\', \'apiVersion\': \'v1\', \'details\': {\'causes\': [{\'field\': \'spec.template.spec.containers[0].livenessProbe.successThreshold\', \'reason\': \'FieldValueInvalid\', \'message\': \'Invalid value: 3: must be 1\'}], \'kind\': \'ReplicationController\', \'name\': \'app-v47-cmd\'}}', 'app-v47-cmd', 'app')]
```

**Comment by bacongobbler** [comment]
Interesting! I guess we should just remove the success threshold flag and restrict the failure threshold if it's that restrictive.

**Comment by helgi** [comment]
http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_probe Only liveness is restricted to 1, assume readiness allows more

**Comment by helgi** [comment]
We should add some guard rails around this or like @bacongobbler said disallow setting threshold on liveness (but allow on readiness)

**Comment by bacongobbler** [comment]
Are these values ever expected to change? Personally I'd hate putting guard rails around these settings in the client then keep watching for changes every k8s release.

**Comment by helgi** [comment]
On one hand I don't imagine it changing too much since threshold 1 on liveness makes sense but if you look at ELBs for example then you can do threshold pretty granular and k8s may try to emulate that eventually.
