### ISSUE TITLE
Allow health and liveness checks per-process type 

### ISSUE THREAD

**Issue by slack** [deis/controller#881]
Relates to #879

After health checks are moved routeable process types by default, we should support setting process-type specific health checks.

`deis healthcheck:{list,set,unset}` should take a new argument `--type=<proc type>`

The list option should either enumerate checks for all process types by default or take an `--all` flag.

**Comment by darkhelmet** [comment]
So I assume you'd be able to provide a `readiness` check for each process type? Our use case is we want the default for `cmd` (webapp) and then an `exec` `readiness` check for `sidekiq`

**Comment by slack** [comment]
Exactly, that type of separation is what we are shooting for!
