### ISSUE TITLE
Create a service for non-web process types

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#883]
Right now there is no way for a web process to discover a worker process in the same namespace. This would be incredibly useful for apps that need to ship the request to a queue for processing, for example. By creating a service but not making it routable, a web process could discover and ship information to the worker through DNS.

Another example comes from this thread on deis-users: https://groups.google.com/forum/#!topic/deis-users/F8G6rrDsmEk

**Comment by helgi** [comment]
How do we imagine this working? For a service to work we need to have a port defined and it is not possible to set `$PORT` per proc type as things stand.

I'd be all for doing this given that k8s DNS is super helpful if a user wants to create their little micro-service setup using that (vs creating many distinct apps I suppose).

**Comment by bacongobbler** [comment]
kinda ugly, but couldn't we just create a service that exposes every port from 1 to 61000 (the typical max for the ephemeral port range) since all the traffic is internal?

**Comment by helgi** [comment]
Yeah that would work. Not the best given security et all but we could technically include linkerd (or similar) to help with that if we really felt badly about it.

The other option is to require people to define port (and as an extension support per proc type configuration, at least for port).

@bacongobbler your idea is the simplest but it is hard to back down from "all open" if we go with that as MVP. Tho technically we could do that and when people define `$PORT` or whatever if we ever do per proc type then we'd only expose that port (or ports)

That might be viable?

**Comment by bacongobbler** [comment]
closing as something we cannot fix
