### ISSUE TITLE
config:push > This action could not be completed due to a conflict.

### ISSUE THREAD

**Issue by JeanMertz** [deis/controller#889]
At first, I thought this was a bug, but then I noticed the error only showed up if the local config file was the same as the remote config.

It would be nice if the error was a bit more descriptive.

**Comment by helgi** [comment]
Can you paste the error here?

The controller returns a "nothing changed" message. https://github.com/deis/controller/blob/master/rootfs/api/models/release.py#L495 So I want to verify. Suspecting the CLI might munge it

**Comment by bacongobbler** [comment]
Yep: https://github.com/deis/controller-sdk-go/blob/b269b5ed0f744b8c5f97898272fdeb43dea8af66/errors.go#L54

**Comment by JeanMertz** [comment]
Yep, that's indeed the error returned, thanks for looking into this. I'll close this one, since there's an issue in place at the correct repository 👍
