### ISSUE TITLE
Return custom message for app not found 404

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/controller#893]
For context, see deis/workflow-cli#77

This would allow the cli to give a specific error message if an application isn't found, such as `Error: Application foo not found` rather than just the generic `Error: Not Found` that is currently logged.

**Comment by helgi** [comment]
This is not going to be all that easy iirc, we use a `get_object_or_404` which raises a generic `404`,  we'd have to add our own logic to replace that if we wanted the custom message
