### ISSUE TITLE
deis pull of image from internal registry should work

### ISSUE THREAD

**Issue by kmala** [deis/controller#894]
You should be able to do a `deis pull <regsitry-ip>:<port>/iamge:tag` basically pull an image already in registry.
we need to remove the striping logic https://github.com/deis/controller/blob/64547741ae6e80f8299992fc57b87d9c10d2c5bd/rootfs/api/models/release.py#L58-L59 as we had removed the registry appending logic in https://github.com/deis/controller/pull/716

**Comment by helgi** [comment]
https://github.com/deis/controller/commit/54c4d727e38d52b13299cbe2399965fbe4dddd10 is the original addition, mostly to note there is more than just the one function

As far as #716 - I'm confused, that PR adds the registry URL in the Release class and removes it from the Scheduler.

What problem are you seeing exactly? The IP / Port are not accessible through the right ENV Vars when we use the registry proxy?

**Comment by kmala** [comment]
In https://github.com/deis/controller/commit/54c4d727e38d52b13299cbe2399965fbe4dddd10 the two functions are image and publish where the change are made. In the image function we removed the striping of the registry endpoint as it is going to be appended in the scheduler before setting in the rc(as every image is going to be in the internal registry).
#716 removed the logic of adding registry to the image in the scheduler as part of initial work for pulling images from private registry which we are not going to store in the internal registry.It added logic to append the registry url for the dockerfile apps and normal deis pull apps but din't add for the `deis pull` of the internal registry apps.
