### ISSUE TITLE
deis config:list missing some envvars

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#927]
When running `deis config:list`, some environment variables available in the latest config is not present. For example:

```
$ deis config:list -a myapp | grep -ic HEALTHCHECK_URL
0
>>> a = models.App.objects.get(id='myapp')
>>> c = a.config_set.latest()
>>> 'HEALTHCHECK_URL' in c.values.keys()
True
```

This is because we retrieve the queryset through the latest release object for an application: 

v1: https://github.com/deis/deis/blob/v1.13.2/controller/api/views.py#L174-L176
v2: https://github.com/deis/controller/blob/v2.2.1/rootfs/api/views.py#L176-L178

This seems to be an edge case where the latest release object does not have this environment variable available. The only way to remove it would be to manually drop into a shell and set the value to None, then scale down/up the processes or roll a new release:

```
c.values['HEALTHCHECK_URL'] = None
c.save()
```

**Comment by helgi** [comment]
If you are specifically looking for `HEALTHCHECK_` items then they wouldn't be shown due to https://github.com/deis/controller/blob/v2.2.1/rootfs/api/models/config.py#L71 which already unsets them

**Comment by bacongobbler** [comment]
The problem is that those keys seem to be present in the latest Config object, but not in the Release object. There's some internal API conflicts going on where a user is noticing certain HEALTHCHECK variables still present in the latest config (at least on Deis v1.12), but they cannot unset those envvars because the latest Release object is referring to a different Config object without those HEALTHCHECK envvars.

**Comment by helgi** [comment]
Have we been able to reproduce this for 2.x?

**Comment by bacongobbler** [comment]
I have not, however I notice the same code being used to fetch the config object is the same in v2 as in v1. We're not sure how to reproduce it, just documenting its effect.

**Comment by bacongobbler** [comment]
haven't seen this ever come up in the wild other than in one custom cluster. Will re-open if this pops up again.
