### ISSUE TITLE
`pod_state` in Scheduler doesn't always return an object

### ISSUE THREAD

**Issue by helgi** [deis/controller#956]
> Error: Unknown Error (503): {"detail":"test-549743504-run-mpnw2 (run): unorderable types: str() < PodState()"}`

This happens when `pod_state` encounters a state it doesn't know about (see `states.get(pod_state, pod_state)`) - This was initially done so `pod_list` in `App` would show *something* instead of crapping out, even if we don't know about the type.

However `run` in the Scheduler assumes the state is always an `object` - a simple type check should work

```
state = self.pod_state(self.get_pod(namespace, name).json())
# States below up do not have logs
if state < PodState.up:
```

**Comment by Joshua-Anderson** [comment]
This was found in [this e2e run](https://ci.deis.io/job/workflow-test-pr/4717/console)

**Comment by vdice** [comment]
Log artifacts from e2e run mentioned attached.  [workflow-test-pr-4717-logs.gz](https://github.com/deis/controller/files/404739/workflow-test-pr-4717-logs.gz)
