### ISSUE TITLE
increase scheduler module test coverage

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#960]
See https://codecov.io/gh/deis/controller/tree/544f4925241f48b0f08fe9b5b087bfa511d67993/rootfs/scheduler

**Comment by helgi** [comment]
I don't think this needs a dedicated ticket but we can keep it... It only dropped due to moving away from using RCs so there is no test coverage for a lot of those code paths.

I'm working on something locally already for this so I am assigning this to myself

**Comment by helgi** [comment]
https://github.com/deis/controller/pull/965 increased it by almost 4% - The rest are a little annoying to get to. Will come back to that at some point

**Comment by helgi** [comment]
https://codecov.io/gh/deis/controller/tree/cebd7364c929f920a6414f6d1629c9877309bdea/rootfs/scheduler

**Comment by bacongobbler** [comment]
states and utils are fully covered which were my main concerns. Let's close this and re-open issues specific to increasing test coverage as time goes on. :)
