### ISSUE TITLE
Pushing a large image times out

### ISSUE THREAD

**Issue by arschles** [deis/controller#971]
After creating an app with `deis create --no-remote cf-broker-sample`, running this command:

```console
deis pull quay.io/arschles/cloudfoundry-github-service-broker:devel -a cf-broker-sample
```

Eventually times out with a 502. Controller logs show the following just before the exception trace:

```console
INFO:registry.dockerclient:Pulling Docker image quay.io/arschles/cloudfoundry-github-service-broker:devel
INFO Tagging Docker image quay.io/arschles/cloudfoundry-github-service-broker:devel as localhost:5555/cf-broker-sample:v2
INFO:registry.dockerclient:Tagging Docker image quay.io/arschles/cloudfoundry-github-service-broker:devel as localhost:5555/cf-broker-sample:v2
INFO Pushing Docker image localhost:5555/cf-broker-sample:v2
INFO:registry.dockerclient:Pushing Docker image localhost:5555/cf-broker-sample:v2
```

Additional notes:

- After the `deis pull` is issued and before the timeout, the registry goes into `CrashLoopBackOff`
- Proxy logs reflect the previous:

  ```console
  2016/08/11 17:09:04 [error] 7#7: *189 upstream timed out (110: Connection timed out) while   connecting to upstream, client: 10.156.2.1, server: localhost, request: "POST /v2/cf-broker-sample/blobs/uploads/ HTTP/1.1", upstream: "http://10.159.247.17:80/v2/cf-broker-sample/blobs/uploads/", host: "localhost:5555"
  ```

This is running on an out of the box install of workflow-v2.3.0, using an in-cluster database and minio for storage.

Note: this issue is probably related to https://github.com/deis/registry/issues/62

**Comment by helgi** [comment]
Pretty sure it is only related to the registry components - You can set an env var to have a longer timeout in the local registry client in the controller tho

**Comment by bacongobbler** [comment]
@arschles I would think this is definitely related to deis/reigstry#62. A better controller error message would be nice, but I agree that this is a registry issue

**Comment by arschles** [comment]
Ok, closing in favor of https://github.com/deis/registry/issues/62
