### ISSUE TITLE
support min/max limits for `deis limits`

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#982]
Right now Workflow supports only the maximum CPU/memory constraints for an application. Now that we are on Kubernetes, it has support for setting both the minimum and the maximum limits. We should also support that in the API/client.

See https://github.com/kubernetes/kubernetes/blob/master/docs/design/admission_control_limit_range.md

**Comment by helgi** [comment]
The way use limits / requests is in term of http://kubernetes.io/docs/user-guide/compute-resources/ which only supports one value, not min/max

the LimitRange resource is a different beast which has to do with controlling general default values of what is used on Containers (same place the above is applied on) and admission control dealio

**Comment by bacongobbler** [comment]
Sounds good. I was opening a ticket for someone on Slack (@sstarcher, I believe). I'm gonna close this for now then unless Shane has something else he'd like to add :)

**Comment by helgi** [comment]
Could become a global setting or something outside of our normal limits - I only wanted to explain the difference :)
