### ISSUE TITLE
Proposal: App info should include internal service IP

### ISSUE THREAD

**Issue by krancour** [deis/controller#987]
This PR is the server-side complement to the proposal at deis/workflow-cli#184

**Comment by bacongobbler** [comment]
We have precedence to not expose internal information about the cluster to the pod. See https://github.com/deis/deis/issues/1078#issuecomment-74879266 and https://github.com/deis/deis/pull/3108.

**Comment by bacongobbler** [comment]
I'm going to close this because of the past precedent about exposing any internal information through the API (including `deis logs` or `deis apps:info`).
